#!/bin/sh

# this is a hacky... todo fixup
verbose=false
if [ "$1" = "-v" ]; then
        verbose=true
        source_file=${2:-"src/main.c"}
        output_file=${3:-"bin/$(basename "$(pwd)")"}
else
        source_file=${1:-"src/main.c"}
        output_file=${2:-"bin/$(basename "$(pwd)")"}
fi

cleanup() {
        pkill -f "$output_file" 2>/dev/null
        wait
        exit 0
}

clear

trap cleanup INT TERM

if [ "$verbose" = true ]; then
        sh /standard/build -v "$source_file" "$output_file"
else
        sh /standard/build "$source_file" "$output_file"
fi

"$output_file" &

inotifywait -m -e modify "$source_file" | while read -r path action file; do
        clear

        pkill -f "$output_file" 2>/dev/null
        sleep 0.1

        if [ "$verbose" = true ]; then
                sh /standard/build -v "$source_file" "$output_file"
        else
                sh /standard/build "$source_file" "$output_file"
        fi

        if [ $? -eq 0 ]; then
                "$output_file" &
        fi
done
