#!/bin/sh

source_file=${1:-"src/main.c"}
output_file=${2:-"bin/$(basename "$(pwd)")"}

cleanup() {
        pkill -f "$output_file" 2>/dev/null
        wait
        exit 0
}

clear

trap cleanup INT TERM

sh /standard/build "$source_file" "$output_file" && "$output_file" &

inotifywait -m -e modify "$source_file" | while read -r path action file; do
        clear

        pkill -f "$output_file" 2>/dev/null
        sleep 0.1

        sh /standard/build "$source_file" "$output_file" && "$output_file" &
done
