#!/bin/sh

source_file=${1:-"src/main.c"}
output_file=${2:-"bin/$(basename "$(pwd)")"}

sh /standard/build $source_file $output_file

$output_file

if [ $? -ne 0 ]; then
        echo "Exited with $?"
fi
