#include "../compiler_memory.c"
/*
        Every byte, every stop position and every source length that is known
        where the call is written.

        Generated by kit/exact_family.py -- do not edit by hand; edit that and
        run it again. It is src/test/exact.c's sibling and has its shape for
        its reason: a size, a byte or a string length that arrives from a loop
        counter reaches none of the expansions, because the choice is made by
        the compiler from the token. So all of them are written out.

        memory_fill is checked with a folded zero and with a folded byte that
        is not zero, because the two take different lines above thirty two
        bytes and only one of them is new. memory_zero is checked beside them
        because it is the same expansion with the byte already chosen.

        memory_copy_until gets the strictest check here. Its answer is a
        pointer, its copy length is the stop position and not the size, and
        the bytes past the one it stopped on belong to the caller -- so the
        whole arena outside what was copied is compared against the pattern it
        was prepared with, not only the guards either side of it. An expansion
        that laid down the whole span would pass every check that looked at
        the copied prefix alone.

        string_copy_end takes its length from a string literal rather than a
        number, since that is where stpcpy's length actually comes from, and
        the expansion is reached through __builtin_strlen folding the literal.
        A length the compiler cannot fold, and one at or past the cutoff, both
        go to the routine, and the last three lengths here are there to say so.
*/

#define TOP 136
#define GUARD 32
#define SKEWS 4

static p8 arena[GUARD + TOP + GUARD];
static p8 quarry[TOP + SKEWS];

static positive checks;
static positive failures;

#define FIELD (arena + GUARD)

//      A pattern that differs at every index, so a write that lands one byte
//      off is visible wherever it lands.
static p8 guard_byte(positive i) { return (p8)(0x27 ^ (i * 7)); }

static fn fail(const p8 address_to what, positive size, const p8 address_to why)
{
        failures++;
        string_format(log, "FAIL %s at %p: %s\n", what, size, why);
}

static fn prepare(void)
{
        for (positive i = 0; i < sizeof(arena); i++) arena[i] = guard_byte(i);
}

/*      The arena outside [from, until) still holds the pattern prepare left.
        This is the whole of the tail check as well as the guard check: past
        the length a routine promised to write, every byte is somebody else's. */
static bool untouched(const p8 address_to what, positive size,
                      positive from, positive until)
{
        for (positive i = 0; i < sizeof(arena); i++) {
                if (i >= from && i < until) continue;
                if (arena[i] != guard_byte(i)) {
                        fail(what, size, i < from ? (const p8 address_to)"wrote before the front"
                                                  : (const p8 address_to)"wrote past the end");
                        return 0;
                }
        }
        return 1;
}

static fn inspect_byte(const p8 address_to what, positive size, p8 want)
{
        checks++;
        if (!untouched(what, size, GUARD, GUARD + size)) return;
        for (positive i = 0; i < size; i++)
                if (FIELD[i] != want) {
                        fail(what, size, (const p8 address_to)"wrong byte");
                        return;
                }
}

#define CHECK_FILL(K)                                                         \
        do {                                                                  \
                prepare();                                                    \
                memory_fill(FIELD, 0, K);                                     \
                inspect_byte((const p8 address_to)"memory_fill zero", K, 0);  \
                prepare();                                                    \
                memory_fill(FIELD, 0x5a, K);                                  \
                inspect_byte((const p8 address_to)"memory_fill byte", K, 0x5a); \
                prepare();                                                    \
                memory_zero(FIELD, K);                                        \
                inspect_byte((const p8 address_to)"memory_zero", K, 0);       \
        } while (0)

/*      Every stop position the size allows, and the position past the end,
        which is the byte being absent and the answer being nothing. */
#define CHECK_UNTIL(K)                                                        \
        do {                                                                  \
                for (positive skew = 0; skew < SKEWS; skew++)                 \
                for (positive at = 0; at <= K; at++) {                        \
                        const p8 address_to from = quarry + skew;             \
                        positive taken = at < K ? at + 1 : K;                 \
                        address_any want = at < K                             \
                                ? (address_any)(FIELD + at + 1) : null;       \
                        address_any answer;                                   \
                                                                              \
                        for (positive i = 0; i < K; i++)                      \
                                ((p8 address_to)from)[i] = (p8)('A' + (i & 7)); \
                        if (at < K) ((p8 address_to)from)[at] = 0x5a;         \
                                                                              \
                        prepare();                                            \
                        checks++;                                             \
                        answer = memory_copy_until(FIELD, (address_any)from,  \
                                                   0x5a, K);                  \
                        if (answer != want) {                                 \
                                fail((const p8 address_to)"memory_copy_until", \
                                     K, (const p8 address_to)"wrong answer"); \
                                continue;                                     \
                        }                                                     \
                        if (!untouched((const p8 address_to)"memory_copy_until", \
                                       K, GUARD, GUARD + taken))              \
                                continue;                                     \
                        for (positive i = 0; i < taken; i++)                  \
                                if (FIELD[i] != from[i]) {                    \
                                        fail((const p8 address_to)"memory_copy_until", \
                                             K, (const p8 address_to)"wrong byte"); \
                                        break;                                \
                                }                                             \
                } while (0);                                                  \
        } while (0)

/*      The literal is the length. The terminator is copied with the rest and
        the answer is where it landed. */
#define CHECK_END(K, TEXT)                                                    \
        do {                                                                  \
                string_address text = (string_address)(TEXT);                 \
                p8 address_to answer;                                         \
                                                                              \
                prepare();                                                    \
                checks++;                                                     \
                answer = string_copy_end(FIELD, (string_address)(TEXT));      \
                if (answer != FIELD + (K)) {                                  \
                        fail((const p8 address_to)"string_copy_end", K,       \
                             (const p8 address_to)"wrong answer");            \
                        break;                                                \
                }                                                             \
                if (!untouched((const p8 address_to)"string_copy_end", K,     \
                               GUARD, GUARD + (K) + 1))                       \
                        break;                                                \
                if (answer[0] != end) {                                       \
                        fail((const p8 address_to)"string_copy_end", K,       \
                             (const p8 address_to)"no terminator");           \
                        break;                                                \
                }                                                             \
                for (positive i = 0; i < (K); i++)                            \
                        if (FIELD[i] != text[i]) {                            \
                                fail((const p8 address_to)"string_copy_end", K, \
                                     (const p8 address_to)"wrong byte");      \
                                break;                                        \
                        }                                                     \
        } while (0)

//      Lengths built by doubling, so a literal of any length is a handful of
//      tokens rather than a line of quoted bytes.
#define A1  "a"
#define A2  A1 A1
#define A4  A2 A2
#define A8  A4 A4
#define A16 A8 A8
#define A32 A16 A16
#define A64 A32 A32
#define A128 A64 A64

b32 main(void)
{
        //      memory_fill with a folded byte, and memory_zero beside it.
        CHECK_FILL(0); CHECK_FILL(1); CHECK_FILL(2); CHECK_FILL(3); CHECK_FILL(4); CHECK_FILL(5); CHECK_FILL(6); CHECK_FILL(7);
        CHECK_FILL(8); CHECK_FILL(9); CHECK_FILL(10); CHECK_FILL(11); CHECK_FILL(12); CHECK_FILL(13); CHECK_FILL(14); CHECK_FILL(15);
        CHECK_FILL(16); CHECK_FILL(17); CHECK_FILL(18); CHECK_FILL(19); CHECK_FILL(20); CHECK_FILL(21); CHECK_FILL(22); CHECK_FILL(23);
        CHECK_FILL(24); CHECK_FILL(25); CHECK_FILL(26); CHECK_FILL(27); CHECK_FILL(28); CHECK_FILL(29); CHECK_FILL(30); CHECK_FILL(31);
        CHECK_FILL(32); CHECK_FILL(33); CHECK_FILL(34); CHECK_FILL(35); CHECK_FILL(36); CHECK_FILL(37); CHECK_FILL(38); CHECK_FILL(39);
        CHECK_FILL(40); CHECK_FILL(41); CHECK_FILL(42); CHECK_FILL(43); CHECK_FILL(44); CHECK_FILL(45); CHECK_FILL(46); CHECK_FILL(47);
        CHECK_FILL(48); CHECK_FILL(49); CHECK_FILL(50); CHECK_FILL(51); CHECK_FILL(52); CHECK_FILL(53); CHECK_FILL(54); CHECK_FILL(55);
        CHECK_FILL(56); CHECK_FILL(57); CHECK_FILL(58); CHECK_FILL(59); CHECK_FILL(60); CHECK_FILL(61); CHECK_FILL(62); CHECK_FILL(63);
        CHECK_FILL(64); CHECK_FILL(65); CHECK_FILL(66); CHECK_FILL(67); CHECK_FILL(68); CHECK_FILL(69); CHECK_FILL(70); CHECK_FILL(71);
        CHECK_FILL(72); CHECK_FILL(73); CHECK_FILL(74); CHECK_FILL(75); CHECK_FILL(76); CHECK_FILL(77); CHECK_FILL(78); CHECK_FILL(79);
        CHECK_FILL(80); CHECK_FILL(81); CHECK_FILL(82); CHECK_FILL(83); CHECK_FILL(84); CHECK_FILL(85); CHECK_FILL(86); CHECK_FILL(87);
        CHECK_FILL(88); CHECK_FILL(89); CHECK_FILL(90); CHECK_FILL(91); CHECK_FILL(92); CHECK_FILL(93); CHECK_FILL(94); CHECK_FILL(95);
        CHECK_FILL(96); CHECK_FILL(97); CHECK_FILL(98); CHECK_FILL(99); CHECK_FILL(100); CHECK_FILL(101); CHECK_FILL(102); CHECK_FILL(103);
        CHECK_FILL(104); CHECK_FILL(105); CHECK_FILL(106); CHECK_FILL(107); CHECK_FILL(108); CHECK_FILL(109); CHECK_FILL(110); CHECK_FILL(111);
        CHECK_FILL(112); CHECK_FILL(113); CHECK_FILL(114); CHECK_FILL(115); CHECK_FILL(116); CHECK_FILL(117); CHECK_FILL(118); CHECK_FILL(119);
        CHECK_FILL(120); CHECK_FILL(121); CHECK_FILL(122); CHECK_FILL(123); CHECK_FILL(124); CHECK_FILL(125); CHECK_FILL(126); CHECK_FILL(127);
        CHECK_FILL(128);
        //      memccpy, every stop position, either side of KNOWN_UNTIL_MAX.
        CHECK_UNTIL(0); CHECK_UNTIL(1); CHECK_UNTIL(2); CHECK_UNTIL(3); CHECK_UNTIL(4); CHECK_UNTIL(5); CHECK_UNTIL(6); CHECK_UNTIL(7);
        CHECK_UNTIL(8); CHECK_UNTIL(9); CHECK_UNTIL(10); CHECK_UNTIL(11); CHECK_UNTIL(12); CHECK_UNTIL(13); CHECK_UNTIL(14); CHECK_UNTIL(15);
        CHECK_UNTIL(16); CHECK_UNTIL(17); CHECK_UNTIL(18); CHECK_UNTIL(19); CHECK_UNTIL(20); CHECK_UNTIL(21); CHECK_UNTIL(22); CHECK_UNTIL(23);
        CHECK_UNTIL(24); CHECK_UNTIL(25); CHECK_UNTIL(26); CHECK_UNTIL(27); CHECK_UNTIL(28); CHECK_UNTIL(29); CHECK_UNTIL(30); CHECK_UNTIL(31);
        CHECK_UNTIL(32); CHECK_UNTIL(40); CHECK_UNTIL(48); CHECK_UNTIL(64); CHECK_UNTIL(96); CHECK_UNTIL(128);
        //      stpcpy, the length coming from the literal itself. The last
        //      three are at and past the cutoff and reach the routine.
        CHECK_END(0, ""); CHECK_END(1, A1); CHECK_END(2, A2); CHECK_END(3, A2 A1);
        CHECK_END(4, A4); CHECK_END(5, A4 A1); CHECK_END(6, A4 A2); CHECK_END(7, A4 A2 A1);
        CHECK_END(8, A8); CHECK_END(9, A8 A1); CHECK_END(10, A8 A2); CHECK_END(11, A8 A2 A1);
        CHECK_END(12, A8 A4); CHECK_END(13, A8 A4 A1); CHECK_END(14, A8 A4 A2); CHECK_END(15, A8 A4 A2 A1);
        CHECK_END(16, A16); CHECK_END(17, A16 A1); CHECK_END(18, A16 A2); CHECK_END(19, A16 A2 A1);
        CHECK_END(20, A16 A4); CHECK_END(21, A16 A4 A1); CHECK_END(22, A16 A4 A2); CHECK_END(23, A16 A4 A2 A1);
        CHECK_END(24, A16 A8); CHECK_END(25, A16 A8 A1); CHECK_END(26, A16 A8 A2); CHECK_END(27, A16 A8 A2 A1);
        CHECK_END(28, A16 A8 A4); CHECK_END(29, A16 A8 A4 A1); CHECK_END(30, A16 A8 A4 A2); CHECK_END(31, A16 A8 A4 A2 A1);
        CHECK_END(32, A32); CHECK_END(33, A32 A1); CHECK_END(34, A32 A2); CHECK_END(35, A32 A2 A1);
        CHECK_END(36, A32 A4); CHECK_END(37, A32 A4 A1); CHECK_END(38, A32 A4 A2); CHECK_END(39, A32 A4 A2 A1);
        CHECK_END(40, A32 A8); CHECK_END(41, A32 A8 A1); CHECK_END(42, A32 A8 A2); CHECK_END(43, A32 A8 A2 A1);
        CHECK_END(44, A32 A8 A4); CHECK_END(45, A32 A8 A4 A1); CHECK_END(46, A32 A8 A4 A2); CHECK_END(47, A32 A8 A4 A2 A1);
        CHECK_END(48, A32 A16); CHECK_END(49, A32 A16 A1); CHECK_END(50, A32 A16 A2); CHECK_END(51, A32 A16 A2 A1);
        CHECK_END(52, A32 A16 A4); CHECK_END(53, A32 A16 A4 A1); CHECK_END(54, A32 A16 A4 A2); CHECK_END(55, A32 A16 A4 A2 A1);
        CHECK_END(56, A32 A16 A8); CHECK_END(57, A32 A16 A8 A1); CHECK_END(58, A32 A16 A8 A2); CHECK_END(59, A32 A16 A8 A2 A1);
        CHECK_END(60, A32 A16 A8 A4); CHECK_END(61, A32 A16 A8 A4 A1); CHECK_END(62, A32 A16 A8 A4 A2); CHECK_END(63, A32 A16 A8 A4 A2 A1);
        CHECK_END(64, A64); CHECK_END(65, A64 A1); CHECK_END(66, A64 A2); CHECK_END(67, A64 A2 A1);
        CHECK_END(68, A64 A4); CHECK_END(69, A64 A4 A1); CHECK_END(70, A64 A4 A2); CHECK_END(71, A64 A4 A2 A1);
        CHECK_END(72, A64 A8); CHECK_END(73, A64 A8 A1); CHECK_END(74, A64 A8 A2); CHECK_END(75, A64 A8 A2 A1);
        CHECK_END(76, A64 A8 A4); CHECK_END(77, A64 A8 A4 A1); CHECK_END(78, A64 A8 A4 A2); CHECK_END(79, A64 A8 A4 A2 A1);
        CHECK_END(80, A64 A16); CHECK_END(81, A64 A16 A1); CHECK_END(82, A64 A16 A2); CHECK_END(83, A64 A16 A2 A1);
        CHECK_END(84, A64 A16 A4); CHECK_END(85, A64 A16 A4 A1); CHECK_END(86, A64 A16 A4 A2); CHECK_END(87, A64 A16 A4 A2 A1);
        CHECK_END(88, A64 A16 A8); CHECK_END(89, A64 A16 A8 A1); CHECK_END(90, A64 A16 A8 A2); CHECK_END(91, A64 A16 A8 A2 A1);
        CHECK_END(92, A64 A16 A8 A4); CHECK_END(93, A64 A16 A8 A4 A1); CHECK_END(94, A64 A16 A8 A4 A2); CHECK_END(95, A64 A16 A8 A4 A2 A1);
        CHECK_END(96, A64 A32); CHECK_END(97, A64 A32 A1); CHECK_END(98, A64 A32 A2); CHECK_END(99, A64 A32 A2 A1);
        CHECK_END(100, A64 A32 A4); CHECK_END(101, A64 A32 A4 A1); CHECK_END(102, A64 A32 A4 A2); CHECK_END(103, A64 A32 A4 A2 A1);
        CHECK_END(104, A64 A32 A8); CHECK_END(105, A64 A32 A8 A1); CHECK_END(106, A64 A32 A8 A2); CHECK_END(107, A64 A32 A8 A2 A1);
        CHECK_END(108, A64 A32 A8 A4); CHECK_END(109, A64 A32 A8 A4 A1); CHECK_END(110, A64 A32 A8 A4 A2); CHECK_END(111, A64 A32 A8 A4 A2 A1);
        CHECK_END(112, A64 A32 A16); CHECK_END(113, A64 A32 A16 A1); CHECK_END(114, A64 A32 A16 A2); CHECK_END(115, A64 A32 A16 A2 A1);
        CHECK_END(116, A64 A32 A16 A4); CHECK_END(117, A64 A32 A16 A4 A1); CHECK_END(118, A64 A32 A16 A4 A2); CHECK_END(119, A64 A32 A16 A4 A2 A1);
        CHECK_END(120, A64 A32 A16 A8); CHECK_END(121, A64 A32 A16 A8 A1); CHECK_END(122, A64 A32 A16 A8 A2); CHECK_END(123, A64 A32 A16 A8 A2 A1);
        CHECK_END(124, A64 A32 A16 A8 A4); CHECK_END(125, A64 A32 A16 A8 A4 A1); CHECK_END(126, A64 A32 A16 A8 A4 A2); CHECK_END(127, A64 A32 A16 A8 A4 A2 A1);
        CHECK_END(128, A128); CHECK_END(129, A128 A1);
        string_format(log, "%p checks, %p failures\n", checks, failures);
        log_flush();
        return failures ? 1 : 0;
}
