#include "../library.c"
/*
        Every size that is known where the call is written.

        Generated by kit/exact.py -- do not edit by hand; edit that and run it
        again.

        memory_copy, memory_copy_fast and memory_fill expand in place when the
        size is a literal, and the line they expand to depends on the number: eight
        bytes is a pair of moves, forty is a vector and a remainder, two
        hundred is still a call. Nothing that takes its size from a loop
        counter can reach any of that, because the choice is made by the
        compiler, from the token. So every size is written out here.

        Each check runs into a buffer with guard bytes either side, and both
        halves are looked at: that the bytes asked for arrived, and that the
        bytes either side did not move. A size class that reaches one byte too
        far writes into a guard, and a size class that stops one byte short
        leaves the pattern showing.

        memory_copy is the name memmove is an alias for, so it is slid through
        every overlap in both directions: an expansion that stores before it
        has finished loading is correct on every test that does not overlap.
        memory_copy_fast promises nothing about overlap and is only checked
        where the two do not touch.

        161 sizes, 32 guard bytes, 40 of slide each way.
*/

#define TOP 160
#define GUARD 32
#define SLIDE 40

static p8 model[TOP];
static p8 arena[GUARD + TOP + GUARD];
static p8 field_room[SLIDE + TOP + SLIDE];
static p8 shadow[SLIDE + TOP + SLIDE];
static p8 temp[TOP];

static positive checks;
static positive failures;

#define FIELD (arena + GUARD)

//      The pattern the guards are set to, and the one the model carries. They
//      differ at every index so a copy that lands one byte off is visible.
static p8 guard_byte(positive i) { return (p8)(0x5a ^ (i * 7)); }
static p8 model_byte(positive i) { return (p8)(0xa5 ^ (i * 13)); }

static void fail(const p8 address_to what, positive size, const p8 address_to why)
{
        failures++;
        string_format(log, "FAIL %s at %p: %s\n", what, size, why);
}

static void prepare(void)
{
        for (positive i = 0; i < sizeof(arena); i++)
                arena[i] = guard_byte(i);
}

//      Guards on both sides, and the body against whatever it should hold.
static void inspect(const p8 address_to what, positive size,
                    const p8 address_to want, b32 want_is_byte)
{
        checks++;

        for (positive i = 0; i < GUARD; i++)
                if (arena[i] != guard_byte(i)) {
                        fail(what, size, "wrote before the front");
                        return;
                }

        for (positive i = GUARD + size; i < sizeof(arena); i++)
                if (arena[i] != guard_byte(i)) {
                        fail(what, size, "wrote past the end");
                        return;
                }

        for (positive i = 0; i < size; i++) {
                p8 got = FIELD[i];
                p8 expect = want_is_byte ? want[0] : want[i];

                if (got != expect) {
                        fail(what, size, "wrong byte");
                        return;
                }
        }
}

//      What a move means, spelled out, for the slid cases to be judged against.
static void reference_move(p8 address_to to, const p8 address_to from, positive size)
{
        for (positive i = 0; i < size; i++) temp[i] = from[i];
        for (positive i = 0; i < size; i++) to[i] = temp[i];
}

#define CHECK_COPY(K)                                                         \
        do {                                                                  \
                prepare();                                                    \
                memory_copy_fast(FIELD, model, K);                            \
                inspect((const p8 address_to)"memory_copy_fast", K, model, 0);\
        } while (0)

#define CHECK_FILL(K)                                                         \
        do {                                                                  \
                p8 value = (p8)(0x3c ^ (K));                                  \
                prepare();                                                    \
                memory_fill(FIELD, value, K);                                 \
                inspect((const p8 address_to)"memory_fill", K, &value, 1);    \
        } while (0)

//      Slid through every overlap the size allows, both directions. The shadow
//      carries the same bytes through the reference, and the two are compared
//      across the whole room, so a store that lands outside the size shows up.
#define CHECK_MOVE(K)                                                         \
        do {                                                                  \
                for (b32 slide = -SLIDE; slide <= SLIDE; slide++) {           \
                        p8 address_to from = field_room + SLIDE;              \
                        p8 address_to to = from + slide;                      \
                        p8 address_to shade = shadow + SLIDE + slide;         \
                                                                              \
                        for (positive i = 0; i < sizeof(field_room); i++)     \
                                field_room[i] = shadow[i] = model_byte(i);    \
                                                                              \
                        memory_copy(to, from, K);                             \
                        reference_move(shade, shadow + SLIDE, K);             \
                                                                              \
                        checks++;                                             \
                                                                              \
                        for (positive i = 0; i < sizeof(field_room); i++)     \
                                if (field_room[i] != shadow[i]) {             \
                                        fail((const p8 address_to)"memory_copy", K, \
                                             "differs from a byte at a time");\
                                        break;                                \
                                }                                             \
                }                                                             \
        } while (0)

//      Every size, once. Called once per tier below.
static void sweep(void)
{
        CHECK_COPY(0); CHECK_FILL(0); CHECK_MOVE(0);
        CHECK_COPY(1); CHECK_FILL(1); CHECK_MOVE(1);
        CHECK_COPY(2); CHECK_FILL(2); CHECK_MOVE(2);
        CHECK_COPY(3); CHECK_FILL(3); CHECK_MOVE(3);
        CHECK_COPY(4); CHECK_FILL(4); CHECK_MOVE(4);
        CHECK_COPY(5); CHECK_FILL(5); CHECK_MOVE(5);
        CHECK_COPY(6); CHECK_FILL(6); CHECK_MOVE(6);
        CHECK_COPY(7); CHECK_FILL(7); CHECK_MOVE(7);
        CHECK_COPY(8); CHECK_FILL(8); CHECK_MOVE(8);
        CHECK_COPY(9); CHECK_FILL(9); CHECK_MOVE(9);
        CHECK_COPY(10); CHECK_FILL(10); CHECK_MOVE(10);
        CHECK_COPY(11); CHECK_FILL(11); CHECK_MOVE(11);
        CHECK_COPY(12); CHECK_FILL(12); CHECK_MOVE(12);
        CHECK_COPY(13); CHECK_FILL(13); CHECK_MOVE(13);
        CHECK_COPY(14); CHECK_FILL(14); CHECK_MOVE(14);
        CHECK_COPY(15); CHECK_FILL(15); CHECK_MOVE(15);
        CHECK_COPY(16); CHECK_FILL(16); CHECK_MOVE(16);
        CHECK_COPY(17); CHECK_FILL(17); CHECK_MOVE(17);
        CHECK_COPY(18); CHECK_FILL(18); CHECK_MOVE(18);
        CHECK_COPY(19); CHECK_FILL(19); CHECK_MOVE(19);
        CHECK_COPY(20); CHECK_FILL(20); CHECK_MOVE(20);
        CHECK_COPY(21); CHECK_FILL(21); CHECK_MOVE(21);
        CHECK_COPY(22); CHECK_FILL(22); CHECK_MOVE(22);
        CHECK_COPY(23); CHECK_FILL(23); CHECK_MOVE(23);
        CHECK_COPY(24); CHECK_FILL(24); CHECK_MOVE(24);
        CHECK_COPY(25); CHECK_FILL(25); CHECK_MOVE(25);
        CHECK_COPY(26); CHECK_FILL(26); CHECK_MOVE(26);
        CHECK_COPY(27); CHECK_FILL(27); CHECK_MOVE(27);
        CHECK_COPY(28); CHECK_FILL(28); CHECK_MOVE(28);
        CHECK_COPY(29); CHECK_FILL(29); CHECK_MOVE(29);
        CHECK_COPY(30); CHECK_FILL(30); CHECK_MOVE(30);
        CHECK_COPY(31); CHECK_FILL(31); CHECK_MOVE(31);
        CHECK_COPY(32); CHECK_FILL(32); CHECK_MOVE(32);
        CHECK_COPY(33); CHECK_FILL(33); CHECK_MOVE(33);
        CHECK_COPY(34); CHECK_FILL(34); CHECK_MOVE(34);
        CHECK_COPY(35); CHECK_FILL(35); CHECK_MOVE(35);
        CHECK_COPY(36); CHECK_FILL(36); CHECK_MOVE(36);
        CHECK_COPY(37); CHECK_FILL(37); CHECK_MOVE(37);
        CHECK_COPY(38); CHECK_FILL(38); CHECK_MOVE(38);
        CHECK_COPY(39); CHECK_FILL(39); CHECK_MOVE(39);
        CHECK_COPY(40); CHECK_FILL(40); CHECK_MOVE(40);
        CHECK_COPY(41); CHECK_FILL(41); CHECK_MOVE(41);
        CHECK_COPY(42); CHECK_FILL(42); CHECK_MOVE(42);
        CHECK_COPY(43); CHECK_FILL(43); CHECK_MOVE(43);
        CHECK_COPY(44); CHECK_FILL(44); CHECK_MOVE(44);
        CHECK_COPY(45); CHECK_FILL(45); CHECK_MOVE(45);
        CHECK_COPY(46); CHECK_FILL(46); CHECK_MOVE(46);
        CHECK_COPY(47); CHECK_FILL(47); CHECK_MOVE(47);
        CHECK_COPY(48); CHECK_FILL(48); CHECK_MOVE(48);
        CHECK_COPY(49); CHECK_FILL(49); CHECK_MOVE(49);
        CHECK_COPY(50); CHECK_FILL(50); CHECK_MOVE(50);
        CHECK_COPY(51); CHECK_FILL(51); CHECK_MOVE(51);
        CHECK_COPY(52); CHECK_FILL(52); CHECK_MOVE(52);
        CHECK_COPY(53); CHECK_FILL(53); CHECK_MOVE(53);
        CHECK_COPY(54); CHECK_FILL(54); CHECK_MOVE(54);
        CHECK_COPY(55); CHECK_FILL(55); CHECK_MOVE(55);
        CHECK_COPY(56); CHECK_FILL(56); CHECK_MOVE(56);
        CHECK_COPY(57); CHECK_FILL(57); CHECK_MOVE(57);
        CHECK_COPY(58); CHECK_FILL(58); CHECK_MOVE(58);
        CHECK_COPY(59); CHECK_FILL(59); CHECK_MOVE(59);
        CHECK_COPY(60); CHECK_FILL(60); CHECK_MOVE(60);
        CHECK_COPY(61); CHECK_FILL(61); CHECK_MOVE(61);
        CHECK_COPY(62); CHECK_FILL(62); CHECK_MOVE(62);
        CHECK_COPY(63); CHECK_FILL(63); CHECK_MOVE(63);
        CHECK_COPY(64); CHECK_FILL(64); CHECK_MOVE(64);
        CHECK_COPY(65); CHECK_FILL(65); CHECK_MOVE(65);
        CHECK_COPY(66); CHECK_FILL(66); CHECK_MOVE(66);
        CHECK_COPY(67); CHECK_FILL(67); CHECK_MOVE(67);
        CHECK_COPY(68); CHECK_FILL(68); CHECK_MOVE(68);
        CHECK_COPY(69); CHECK_FILL(69); CHECK_MOVE(69);
        CHECK_COPY(70); CHECK_FILL(70); CHECK_MOVE(70);
        CHECK_COPY(71); CHECK_FILL(71); CHECK_MOVE(71);
        CHECK_COPY(72); CHECK_FILL(72); CHECK_MOVE(72);
        CHECK_COPY(73); CHECK_FILL(73); CHECK_MOVE(73);
        CHECK_COPY(74); CHECK_FILL(74); CHECK_MOVE(74);
        CHECK_COPY(75); CHECK_FILL(75); CHECK_MOVE(75);
        CHECK_COPY(76); CHECK_FILL(76); CHECK_MOVE(76);
        CHECK_COPY(77); CHECK_FILL(77); CHECK_MOVE(77);
        CHECK_COPY(78); CHECK_FILL(78); CHECK_MOVE(78);
        CHECK_COPY(79); CHECK_FILL(79); CHECK_MOVE(79);
        CHECK_COPY(80); CHECK_FILL(80); CHECK_MOVE(80);
        CHECK_COPY(81); CHECK_FILL(81); CHECK_MOVE(81);
        CHECK_COPY(82); CHECK_FILL(82); CHECK_MOVE(82);
        CHECK_COPY(83); CHECK_FILL(83); CHECK_MOVE(83);
        CHECK_COPY(84); CHECK_FILL(84); CHECK_MOVE(84);
        CHECK_COPY(85); CHECK_FILL(85); CHECK_MOVE(85);
        CHECK_COPY(86); CHECK_FILL(86); CHECK_MOVE(86);
        CHECK_COPY(87); CHECK_FILL(87); CHECK_MOVE(87);
        CHECK_COPY(88); CHECK_FILL(88); CHECK_MOVE(88);
        CHECK_COPY(89); CHECK_FILL(89); CHECK_MOVE(89);
        CHECK_COPY(90); CHECK_FILL(90); CHECK_MOVE(90);
        CHECK_COPY(91); CHECK_FILL(91); CHECK_MOVE(91);
        CHECK_COPY(92); CHECK_FILL(92); CHECK_MOVE(92);
        CHECK_COPY(93); CHECK_FILL(93); CHECK_MOVE(93);
        CHECK_COPY(94); CHECK_FILL(94); CHECK_MOVE(94);
        CHECK_COPY(95); CHECK_FILL(95); CHECK_MOVE(95);
        CHECK_COPY(96); CHECK_FILL(96); CHECK_MOVE(96);
        CHECK_COPY(97); CHECK_FILL(97); CHECK_MOVE(97);
        CHECK_COPY(98); CHECK_FILL(98); CHECK_MOVE(98);
        CHECK_COPY(99); CHECK_FILL(99); CHECK_MOVE(99);
        CHECK_COPY(100); CHECK_FILL(100); CHECK_MOVE(100);
        CHECK_COPY(101); CHECK_FILL(101); CHECK_MOVE(101);
        CHECK_COPY(102); CHECK_FILL(102); CHECK_MOVE(102);
        CHECK_COPY(103); CHECK_FILL(103); CHECK_MOVE(103);
        CHECK_COPY(104); CHECK_FILL(104); CHECK_MOVE(104);
        CHECK_COPY(105); CHECK_FILL(105); CHECK_MOVE(105);
        CHECK_COPY(106); CHECK_FILL(106); CHECK_MOVE(106);
        CHECK_COPY(107); CHECK_FILL(107); CHECK_MOVE(107);
        CHECK_COPY(108); CHECK_FILL(108); CHECK_MOVE(108);
        CHECK_COPY(109); CHECK_FILL(109); CHECK_MOVE(109);
        CHECK_COPY(110); CHECK_FILL(110); CHECK_MOVE(110);
        CHECK_COPY(111); CHECK_FILL(111); CHECK_MOVE(111);
        CHECK_COPY(112); CHECK_FILL(112); CHECK_MOVE(112);
        CHECK_COPY(113); CHECK_FILL(113); CHECK_MOVE(113);
        CHECK_COPY(114); CHECK_FILL(114); CHECK_MOVE(114);
        CHECK_COPY(115); CHECK_FILL(115); CHECK_MOVE(115);
        CHECK_COPY(116); CHECK_FILL(116); CHECK_MOVE(116);
        CHECK_COPY(117); CHECK_FILL(117); CHECK_MOVE(117);
        CHECK_COPY(118); CHECK_FILL(118); CHECK_MOVE(118);
        CHECK_COPY(119); CHECK_FILL(119); CHECK_MOVE(119);
        CHECK_COPY(120); CHECK_FILL(120); CHECK_MOVE(120);
        CHECK_COPY(121); CHECK_FILL(121); CHECK_MOVE(121);
        CHECK_COPY(122); CHECK_FILL(122); CHECK_MOVE(122);
        CHECK_COPY(123); CHECK_FILL(123); CHECK_MOVE(123);
        CHECK_COPY(124); CHECK_FILL(124); CHECK_MOVE(124);
        CHECK_COPY(125); CHECK_FILL(125); CHECK_MOVE(125);
        CHECK_COPY(126); CHECK_FILL(126); CHECK_MOVE(126);
        CHECK_COPY(127); CHECK_FILL(127); CHECK_MOVE(127);
        CHECK_COPY(128); CHECK_FILL(128); CHECK_MOVE(128);
        CHECK_COPY(129); CHECK_FILL(129); CHECK_MOVE(129);
        CHECK_COPY(130); CHECK_FILL(130); CHECK_MOVE(130);
        CHECK_COPY(131); CHECK_FILL(131); CHECK_MOVE(131);
        CHECK_COPY(132); CHECK_FILL(132); CHECK_MOVE(132);
        CHECK_COPY(133); CHECK_FILL(133); CHECK_MOVE(133);
        CHECK_COPY(134); CHECK_FILL(134); CHECK_MOVE(134);
        CHECK_COPY(135); CHECK_FILL(135); CHECK_MOVE(135);
        CHECK_COPY(136); CHECK_FILL(136); CHECK_MOVE(136);
        CHECK_COPY(137); CHECK_FILL(137); CHECK_MOVE(137);
        CHECK_COPY(138); CHECK_FILL(138); CHECK_MOVE(138);
        CHECK_COPY(139); CHECK_FILL(139); CHECK_MOVE(139);
        CHECK_COPY(140); CHECK_FILL(140); CHECK_MOVE(140);
        CHECK_COPY(141); CHECK_FILL(141); CHECK_MOVE(141);
        CHECK_COPY(142); CHECK_FILL(142); CHECK_MOVE(142);
        CHECK_COPY(143); CHECK_FILL(143); CHECK_MOVE(143);
        CHECK_COPY(144); CHECK_FILL(144); CHECK_MOVE(144);
        CHECK_COPY(145); CHECK_FILL(145); CHECK_MOVE(145);
        CHECK_COPY(146); CHECK_FILL(146); CHECK_MOVE(146);
        CHECK_COPY(147); CHECK_FILL(147); CHECK_MOVE(147);
        CHECK_COPY(148); CHECK_FILL(148); CHECK_MOVE(148);
        CHECK_COPY(149); CHECK_FILL(149); CHECK_MOVE(149);
        CHECK_COPY(150); CHECK_FILL(150); CHECK_MOVE(150);
        CHECK_COPY(151); CHECK_FILL(151); CHECK_MOVE(151);
        CHECK_COPY(152); CHECK_FILL(152); CHECK_MOVE(152);
        CHECK_COPY(153); CHECK_FILL(153); CHECK_MOVE(153);
        CHECK_COPY(154); CHECK_FILL(154); CHECK_MOVE(154);
        CHECK_COPY(155); CHECK_FILL(155); CHECK_MOVE(155);
        CHECK_COPY(156); CHECK_FILL(156); CHECK_MOVE(156);
        CHECK_COPY(157); CHECK_FILL(157); CHECK_MOVE(157);
        CHECK_COPY(158); CHECK_FILL(158); CHECK_MOVE(158);
        CHECK_COPY(159); CHECK_FILL(159); CHECK_MOVE(159);
        CHECK_COPY(160); CHECK_FILL(160); CHECK_MOVE(160);
}

/*
        Once per tier, not once.

        The wide bodies are chosen at run time, by a byte, and a machine that
        has AVX2 takes that branch every time -- so a whole tier ships having
        never run. That has happened twice in this tree already: a one byte
        sabotage in the AVX2 path of memory_first_of passed the entire suite
        because every case was shorter than a vector.

        So the flag is walked down and the sweep repeated. The narrow tier is
        what a build with no permission to use vectors gets, and what every
        pre-AVX2 machine gets, and it is checked here on a machine that has
        them.
*/
b32 main(void)
{
        moonwater_cpu_detect();

        for (positive i = 0; i < TOP; i++) model[i] = model_byte(i);

        p8 found_avx2 = cpu_has_avx2;
        p8 found_avx512 = cpu_has_avx512;

        for (b32 tier = 0; tier < 2; tier++) {
                cpu_has_avx2 = tier ? 0 : found_avx2;
                cpu_has_avx512 = tier ? 0 : found_avx512;

                positive before = failures;
                sweep();

                string_format(log, "  %s: %p checks, %p failures\n",
                              tier ? (const p8 address_to)"narrow"
                                   : (const p8 address_to)"as found",
                              checks, failures - before);
        }

        cpu_has_avx2 = found_avx2;
        cpu_has_avx512 = found_avx512;

        string_format(log, "%p checks, %p failures\n", checks, failures);
        log_flush();

        return failures ? 1 : 0;
}
