#include "../compiler_memory.c"
/*
        Every length that is known where the call is written.

        Generated by kit/exact_scan.py -- do not edit by hand; edit that and
        run it again.

        memory_compare, memory_first_of and memory_last_of expand in place
        when the length is a literal, and the line they expand to depends on
        the number: four bytes is a pair of loads, twelve is two words that
        overlap, two hundred is still a call. Nothing that takes its length
        from a loop counter can reach any of that, because the choice is made
        by the compiler, from the token. So every length is written out here.

        These three read and never write, so guard bytes either side would
        guard nothing: the mistake available to an expansion here is reading
        past the bound, not writing past it. Two things catch that instead.

        The block is laid against an unmapped page, once at each end, so a
        read of even one byte outside it stops the program rather than
        returning a wrong answer quietly. And in the second half of each
        check the bytes around the block are the very thing being looked
        for, so an expansion that reads too far without faulting still
        answers with a pointer outside the bound or a difference where there
        was none, and the check says so.

        Both the expansion and the routine are held against a byte at a time
        model rather than against each other, because two bodies that share a
        mistake agree with each other perfectly.

        161 lengths, every difference position and every match position for
        each, both ends of the page, and the whole sweep once more with the
        wide flags walked down.
*/

#define TOP 160
#define PAGE 4096
#define PROT_NONE 0
#define PROT_READ_WRITE 3

static p8 address_to first_room;
static p8 address_to second_room;

static positive checks;
static positive failures;

static fn fail(const p8 address_to what, positive size, positive detail,
               const p8 address_to why)
{
        failures++;
        string_format(log, "FAIL %s at %p (%p): %s\n", what, size, detail, why);
}

//      What each of the three means, spelled out a byte at a time, for the
//      other two answers to be judged against.
static b32 model_compare(const p8 address_to left, const p8 address_to right,
                         positive size)
{
        for (positive i = 0; i < size; i++)
                if (left[i] != right[i])
                        return (b32)left[i] - (b32)right[i];
        return 0;
}

static address_any model_first(const p8 address_to block, p8 value, positive size)
{
        for (positive i = 0; i < size; i++)
                if (block[i] == value)
                        return (address_any)(block + i);
        return null;
}

static address_any model_last(const p8 address_to block, p8 value, positive size)
{
        positive i = size;

        while (i) {
                i--;
                if (block[i] == value)
                        return (address_any)(block + i);
        }
        return null;
}

/*
        Three pages, and the two outside ones taken away.

        The middle page is where a block goes. Laid at its front, one byte
        before it is unmapped; laid at its back, one byte past it is. So a
        sweep that runs each length both ways has an unmapped byte on
        whichever side the expansion might have wandered to.
*/
static p8 address_to room(void)
{
        p8 address_to base = (p8 address_to)memory(3 * PAGE);

        if (!base)
                return null;
        system_call_3(syscall(mprotect), (positive)base, PAGE, PROT_NONE);
        system_call_3(syscall(mprotect), (positive)(base + 2 * PAGE), PAGE,
                      PROT_NONE);
        return base + PAGE;
}

//      side 0 puts the block against the unmapped page in front of it, end 1
//      against the one behind it.
static p8 address_to placed(p8 address_to region, positive size, positive side)
{
        return side ? region + PAGE - size : region;
}

#define CHECK_COMPARE(K)                                                      \
        do {                                                                  \
                for (positive side = 0; side < 2; side++) {                      \
                        p8 address_to left = placed(first_room, K, side);       \
                        p8 address_to right = placed(second_room, K, side);     \
                                                                              \
                        for (positive i = 0; i < K; i++)                       \
                                left[i] = right[i] = (p8)(0xa5 ^ (i * 13));   \
                                                                              \
                        for (positive spot = 0; spot <= K; spot++) {          \
                                b32 want, got;                                \
                                                                              \
                                if (spot < K)                                 \
                                        right[spot] = (p8)(left[spot] ^ 0xff);\
                                want = model_compare(left, right, K);         \
                                checks++;                                     \
                                got = compare_known(left, right, K);          \
                                if (got != want)                              \
                                        fail((const p8 address_to)            \
                                             "compare_known", K, spot,        \
                                             "differs from a byte at a time");\
                                checks++;                                     \
                                got = (memory_compare)(left, right, K);       \
                                if (got != want)                              \
                                        fail((const p8 address_to)            \
                                             "memory_compare", K, spot,       \
                                             "differs from a byte at a time");\
                                if (spot < K)                                 \
                                        right[spot] = left[spot];             \
                        }                                                     \
                }                                                             \
        } while (0)

/*
        The same lengths with the block put in the middle of the page and
        every byte around it made to differ, so an expansion that reads past
        the bound sees a difference that is not inside it.
*/
#define CHECK_COMPARE_SURROUNDED(K)                                           \
        do {                                                                  \
                p8 address_to left = first_room + 64;                         \
                p8 address_to right = second_room + 64;                       \
                                                                              \
                for (positive i = 0; i < PAGE - 128; i++) {                   \
                        left[i] = 0x11;                                       \
                        right[i] = 0x22;                                      \
                }                                                             \
                for (positive i = 0; i < 64; i++) {                           \
                        first_room[i] = 0x33;                                 \
                        second_room[i] = 0x44;                                \
                }                                                             \
                for (positive i = 0; i < K; i++)                              \
                        left[i] = right[i] = (p8)(0x5a ^ (i * 7));            \
                checks++;                                                     \
                if (compare_known(left, right, K) != 0)                       \
                        fail((const p8 address_to)"compare_known", K, 0,      \
                             "read past the bound");                          \
                checks++;                                                     \
                if ((memory_compare)(left, right, K) != 0)                    \
                        fail((const p8 address_to)"memory_compare", K, 0,     \
                             "read past the bound");                          \
        } while (0)

#define CHECK_SCAN(K)                                                         \
        do {                                                                  \
                static const p8 wanted[3] = {0x00, 0xa7, 0xff};               \
                                                                              \
                for (positive side = 0; side < 2; side++)                        \
                        for (positive w = 0; w < 3; w++) {                    \
                                p8 needle = wanted[w];                        \
                                p8 address_to block =                         \
                                        placed(first_room, K, side);           \
                                                                              \
                                for (positive i = 0; i < K; i++)              \
                                        block[i] = (p8)(needle ^ 0x5b ^       \
                                                        (i * 29));            \
                                for (positive i = 0; i < K; i++)              \
                                        if (block[i] == needle)               \
                                                block[i] = (p8)(needle ^ 1);  \
                                                                              \
                                for (positive spot = 0; spot <= K; spot++) {  \
                                        address_any want_first;               \
                                        address_any want_last;                \
                                                                              \
                                        if (spot < K)                         \
                                                block[spot] = needle;         \
                                        want_first = model_first(block,       \
                                                                 needle, K);  \
                                        want_last = model_last(block,         \
                                                               needle, K);    \
                                        checks++;                             \
                                        if (first_of_known(block, (b8)needle, \
                                                           K) != want_first)  \
                                                fail((const p8 address_to)    \
                                                     "first_of_known", K,     \
                                                     spot, "wrong answer");   \
                                        checks++;                             \
                                        if ((memory_first_of)(block,          \
                                                              (b8)needle, K)  \
                                            != want_first)                    \
                                                fail((const p8 address_to)    \
                                                     "memory_first_of", K,    \
                                                     spot, "wrong answer");   \
                                        checks++;                             \
                                        if (last_of_known(block, (b8)needle,  \
                                                          K) != want_last)    \
                                                fail((const p8 address_to)    \
                                                     "last_of_known", K,      \
                                                     spot, "wrong answer");   \
                                        checks++;                             \
                                        if ((memory_last_of)(block,           \
                                                             (b8)needle, K)   \
                                            != want_last)                     \
                                                fail((const p8 address_to)    \
                                                     "memory_last_of", K,     \
                                                     spot, "wrong answer");   \
                                        if (spot < K)                         \
                                                block[spot] =                 \
                                                        (p8)(needle ^ 1);     \
                                }                                             \
                        }                                                     \
        } while (0)

/*
        The block in the middle of the page with the byte being looked for
        laid on every side of it. A scan that reads one byte too far finds
        one and answers with an address outside the bound, which the model
        cannot produce and this catches.
*/
#define CHECK_SCAN_SURROUNDED(K)                                              \
        do {                                                                  \
                p8 needle = 0xa7;                                             \
                p8 address_to block = first_room + 64;                        \
                                                                              \
                for (positive i = 0; i < PAGE; i++)                           \
                        first_room[i] = needle;                               \
                for (positive i = 0; i < K; i++)                              \
                        block[i] = (p8)(needle ^ 1);                          \
                checks++;                                                     \
                if (first_of_known(block, (b8)needle, K) != null)             \
                        fail((const p8 address_to)"first_of_known", K, 0,     \
                             "read past the bound");                          \
                checks++;                                                     \
                if ((memory_first_of)(block, (b8)needle, K) != null)          \
                        fail((const p8 address_to)"memory_first_of", K, 0,    \
                             "read past the bound");                          \
                checks++;                                                     \
                if (last_of_known(block, (b8)needle, K) != null)              \
                        fail((const p8 address_to)"last_of_known", K, 0,      \
                             "read before the front");                        \
                checks++;                                                     \
                if ((memory_last_of)(block, (b8)needle, K) != null)           \
                        fail((const p8 address_to)"memory_last_of", K, 0,     \
                             "read before the front");                        \
        } while (0)

/*
        Matches and differences packed together rather than one at a time.

        A sweep that plants a single needle never tells a scan that answers
        with the first match from one that answers with the last, because
        with one match they are the same address. And the cheap carry-free
        zero test marks a byte holding one just above a byte holding zero,
        which only shows when the two are neighbours. So each length is also
        filled from a small alphabet that puts the needle, the needle with
        its bottom bit flipped, and two bytes that are neither, next to each
        other at every spacing the seeds reach.
*/
#define CHECK_DENSE(K)                                                        \
        do {                                                                  \
                p8 needle = 0xa7;                                             \
                                                                              \
                for (positive seed = 1; seed <= 24; seed++) {                 \
                        p8 address_to block = first_room + 64;                \
                        p8 address_to other = second_room + 64;               \
                        address_any want_first;                               \
                        address_any want_last;                                \
                        b32 want_difference;                                  \
                                                                              \
                        for (positive i = 0; i < K; i++) {                    \
                                positive roll = (i * seed + seed * 7) % 5;    \
                                                                              \
                                block[i] = roll == 0 ? needle                 \
                                         : roll == 1 ? (p8)(needle ^ 1)       \
                                         : roll == 2 ? 0                      \
                                         : (p8)(0x5a ^ (i * 11));             \
                                other[i] = (roll == 3) ? (p8)(block[i] ^ 0x80)\
                                                       : block[i];            \
                        }                                                     \
                                                                              \
                        want_first = model_first(block, needle, K);           \
                        want_last = model_last(block, needle, K);             \
                        want_difference = model_compare(block, other, K);     \
                                                                              \
                        checks++;                                             \
                        if (first_of_known(block, (b8)needle, K) != want_first)\
                                fail((const p8 address_to)"first_of_known",   \
                                     K, seed, "wrong match among many");      \
                        checks++;                                             \
                        if ((memory_first_of)(block, (b8)needle, K)           \
                            != want_first)                                    \
                                fail((const p8 address_to)"memory_first_of",  \
                                     K, seed, "wrong match among many");      \
                        checks++;                                             \
                        if (last_of_known(block, (b8)needle, K) != want_last) \
                                fail((const p8 address_to)"last_of_known", K, \
                                     seed, "wrong match among many");         \
                        checks++;                                             \
                        if ((memory_last_of)(block, (b8)needle, K)            \
                            != want_last)                                     \
                                fail((const p8 address_to)"memory_last_of", K,\
                                     seed, "wrong match among many");         \
                        checks++;                                             \
                        if (compare_known(block, other, K) != want_difference)\
                                fail((const p8 address_to)"compare_known", K, \
                                     seed, "wrong difference among many");    \
                        checks++;                                             \
                        if ((memory_compare)(block, other, K)                 \
                            != want_difference)                               \
                                fail((const p8 address_to)"memory_compare", K,\
                                     seed, "wrong difference among many");    \
                                                                              \
                        /*    And once more through the macros themselves,    \
                              which is the only place the cutoff is decided:  \
                              under it these are the expansion and over it    \
                              they are the call, and both have to be right. */\
                        checks++;                                             \
                        if (memory_first_of(block, (b8)needle, K)             \
                            != want_first)                                    \
                                fail((const p8 address_to)"the first_of "     \
                                     "macro", K, seed, "wrong answer");       \
                        checks++;                                             \
                        if (memory_last_of(block, (b8)needle, K) != want_last)\
                                fail((const p8 address_to)"the last_of macro",\
                                     K, seed, "wrong answer");                \
                        checks++;                                             \
                        if (memory_compare(block, other, K) != want_difference)\
                                fail((const p8 address_to)"the compare macro",\
                                     K, seed, "wrong difference");            \
                }                                                             \
        } while (0)

/*
        Every length, once, in bands of twenty.

        One function per band rather than one for the lot, because a length
        that expands to a straight line expands to a long one, and on riscv64
        a single sweep of a hundred and sixty of them puts the far end of the
        function out of reach of its own jumps.
*/
static void sweep_0_19(void)
{
        CHECK_COMPARE(0); CHECK_COMPARE_SURROUNDED(0); CHECK_SCAN(0); CHECK_SCAN_SURROUNDED(0); CHECK_DENSE(0);
        CHECK_COMPARE(1); CHECK_COMPARE_SURROUNDED(1); CHECK_SCAN(1); CHECK_SCAN_SURROUNDED(1); CHECK_DENSE(1);
        CHECK_COMPARE(2); CHECK_COMPARE_SURROUNDED(2); CHECK_SCAN(2); CHECK_SCAN_SURROUNDED(2); CHECK_DENSE(2);
        CHECK_COMPARE(3); CHECK_COMPARE_SURROUNDED(3); CHECK_SCAN(3); CHECK_SCAN_SURROUNDED(3); CHECK_DENSE(3);
        CHECK_COMPARE(4); CHECK_COMPARE_SURROUNDED(4); CHECK_SCAN(4); CHECK_SCAN_SURROUNDED(4); CHECK_DENSE(4);
        CHECK_COMPARE(5); CHECK_COMPARE_SURROUNDED(5); CHECK_SCAN(5); CHECK_SCAN_SURROUNDED(5); CHECK_DENSE(5);
        CHECK_COMPARE(6); CHECK_COMPARE_SURROUNDED(6); CHECK_SCAN(6); CHECK_SCAN_SURROUNDED(6); CHECK_DENSE(6);
        CHECK_COMPARE(7); CHECK_COMPARE_SURROUNDED(7); CHECK_SCAN(7); CHECK_SCAN_SURROUNDED(7); CHECK_DENSE(7);
        CHECK_COMPARE(8); CHECK_COMPARE_SURROUNDED(8); CHECK_SCAN(8); CHECK_SCAN_SURROUNDED(8); CHECK_DENSE(8);
        CHECK_COMPARE(9); CHECK_COMPARE_SURROUNDED(9); CHECK_SCAN(9); CHECK_SCAN_SURROUNDED(9); CHECK_DENSE(9);
        CHECK_COMPARE(10); CHECK_COMPARE_SURROUNDED(10); CHECK_SCAN(10); CHECK_SCAN_SURROUNDED(10); CHECK_DENSE(10);
        CHECK_COMPARE(11); CHECK_COMPARE_SURROUNDED(11); CHECK_SCAN(11); CHECK_SCAN_SURROUNDED(11); CHECK_DENSE(11);
        CHECK_COMPARE(12); CHECK_COMPARE_SURROUNDED(12); CHECK_SCAN(12); CHECK_SCAN_SURROUNDED(12); CHECK_DENSE(12);
        CHECK_COMPARE(13); CHECK_COMPARE_SURROUNDED(13); CHECK_SCAN(13); CHECK_SCAN_SURROUNDED(13); CHECK_DENSE(13);
        CHECK_COMPARE(14); CHECK_COMPARE_SURROUNDED(14); CHECK_SCAN(14); CHECK_SCAN_SURROUNDED(14); CHECK_DENSE(14);
        CHECK_COMPARE(15); CHECK_COMPARE_SURROUNDED(15); CHECK_SCAN(15); CHECK_SCAN_SURROUNDED(15); CHECK_DENSE(15);
        CHECK_COMPARE(16); CHECK_COMPARE_SURROUNDED(16); CHECK_SCAN(16); CHECK_SCAN_SURROUNDED(16); CHECK_DENSE(16);
        CHECK_COMPARE(17); CHECK_COMPARE_SURROUNDED(17); CHECK_SCAN(17); CHECK_SCAN_SURROUNDED(17); CHECK_DENSE(17);
        CHECK_COMPARE(18); CHECK_COMPARE_SURROUNDED(18); CHECK_SCAN(18); CHECK_SCAN_SURROUNDED(18); CHECK_DENSE(18);
        CHECK_COMPARE(19); CHECK_COMPARE_SURROUNDED(19); CHECK_SCAN(19); CHECK_SCAN_SURROUNDED(19); CHECK_DENSE(19);
}

static void sweep_20_39(void)
{
        CHECK_COMPARE(20); CHECK_COMPARE_SURROUNDED(20); CHECK_SCAN(20); CHECK_SCAN_SURROUNDED(20); CHECK_DENSE(20);
        CHECK_COMPARE(21); CHECK_COMPARE_SURROUNDED(21); CHECK_SCAN(21); CHECK_SCAN_SURROUNDED(21); CHECK_DENSE(21);
        CHECK_COMPARE(22); CHECK_COMPARE_SURROUNDED(22); CHECK_SCAN(22); CHECK_SCAN_SURROUNDED(22); CHECK_DENSE(22);
        CHECK_COMPARE(23); CHECK_COMPARE_SURROUNDED(23); CHECK_SCAN(23); CHECK_SCAN_SURROUNDED(23); CHECK_DENSE(23);
        CHECK_COMPARE(24); CHECK_COMPARE_SURROUNDED(24); CHECK_SCAN(24); CHECK_SCAN_SURROUNDED(24); CHECK_DENSE(24);
        CHECK_COMPARE(25); CHECK_COMPARE_SURROUNDED(25); CHECK_SCAN(25); CHECK_SCAN_SURROUNDED(25); CHECK_DENSE(25);
        CHECK_COMPARE(26); CHECK_COMPARE_SURROUNDED(26); CHECK_SCAN(26); CHECK_SCAN_SURROUNDED(26); CHECK_DENSE(26);
        CHECK_COMPARE(27); CHECK_COMPARE_SURROUNDED(27); CHECK_SCAN(27); CHECK_SCAN_SURROUNDED(27); CHECK_DENSE(27);
        CHECK_COMPARE(28); CHECK_COMPARE_SURROUNDED(28); CHECK_SCAN(28); CHECK_SCAN_SURROUNDED(28); CHECK_DENSE(28);
        CHECK_COMPARE(29); CHECK_COMPARE_SURROUNDED(29); CHECK_SCAN(29); CHECK_SCAN_SURROUNDED(29); CHECK_DENSE(29);
        CHECK_COMPARE(30); CHECK_COMPARE_SURROUNDED(30); CHECK_SCAN(30); CHECK_SCAN_SURROUNDED(30); CHECK_DENSE(30);
        CHECK_COMPARE(31); CHECK_COMPARE_SURROUNDED(31); CHECK_SCAN(31); CHECK_SCAN_SURROUNDED(31); CHECK_DENSE(31);
        CHECK_COMPARE(32); CHECK_COMPARE_SURROUNDED(32); CHECK_SCAN(32); CHECK_SCAN_SURROUNDED(32); CHECK_DENSE(32);
        CHECK_COMPARE(33); CHECK_COMPARE_SURROUNDED(33); CHECK_SCAN(33); CHECK_SCAN_SURROUNDED(33); CHECK_DENSE(33);
        CHECK_COMPARE(34); CHECK_COMPARE_SURROUNDED(34); CHECK_SCAN(34); CHECK_SCAN_SURROUNDED(34); CHECK_DENSE(34);
        CHECK_COMPARE(35); CHECK_COMPARE_SURROUNDED(35); CHECK_SCAN(35); CHECK_SCAN_SURROUNDED(35); CHECK_DENSE(35);
        CHECK_COMPARE(36); CHECK_COMPARE_SURROUNDED(36); CHECK_SCAN(36); CHECK_SCAN_SURROUNDED(36); CHECK_DENSE(36);
        CHECK_COMPARE(37); CHECK_COMPARE_SURROUNDED(37); CHECK_SCAN(37); CHECK_SCAN_SURROUNDED(37); CHECK_DENSE(37);
        CHECK_COMPARE(38); CHECK_COMPARE_SURROUNDED(38); CHECK_SCAN(38); CHECK_SCAN_SURROUNDED(38); CHECK_DENSE(38);
        CHECK_COMPARE(39); CHECK_COMPARE_SURROUNDED(39); CHECK_SCAN(39); CHECK_SCAN_SURROUNDED(39); CHECK_DENSE(39);
}

static void sweep_40_59(void)
{
        CHECK_COMPARE(40); CHECK_COMPARE_SURROUNDED(40); CHECK_SCAN(40); CHECK_SCAN_SURROUNDED(40); CHECK_DENSE(40);
        CHECK_COMPARE(41); CHECK_COMPARE_SURROUNDED(41); CHECK_SCAN(41); CHECK_SCAN_SURROUNDED(41); CHECK_DENSE(41);
        CHECK_COMPARE(42); CHECK_COMPARE_SURROUNDED(42); CHECK_SCAN(42); CHECK_SCAN_SURROUNDED(42); CHECK_DENSE(42);
        CHECK_COMPARE(43); CHECK_COMPARE_SURROUNDED(43); CHECK_SCAN(43); CHECK_SCAN_SURROUNDED(43); CHECK_DENSE(43);
        CHECK_COMPARE(44); CHECK_COMPARE_SURROUNDED(44); CHECK_SCAN(44); CHECK_SCAN_SURROUNDED(44); CHECK_DENSE(44);
        CHECK_COMPARE(45); CHECK_COMPARE_SURROUNDED(45); CHECK_SCAN(45); CHECK_SCAN_SURROUNDED(45); CHECK_DENSE(45);
        CHECK_COMPARE(46); CHECK_COMPARE_SURROUNDED(46); CHECK_SCAN(46); CHECK_SCAN_SURROUNDED(46); CHECK_DENSE(46);
        CHECK_COMPARE(47); CHECK_COMPARE_SURROUNDED(47); CHECK_SCAN(47); CHECK_SCAN_SURROUNDED(47); CHECK_DENSE(47);
        CHECK_COMPARE(48); CHECK_COMPARE_SURROUNDED(48); CHECK_SCAN(48); CHECK_SCAN_SURROUNDED(48); CHECK_DENSE(48);
        CHECK_COMPARE(49); CHECK_COMPARE_SURROUNDED(49); CHECK_SCAN(49); CHECK_SCAN_SURROUNDED(49); CHECK_DENSE(49);
        CHECK_COMPARE(50); CHECK_COMPARE_SURROUNDED(50); CHECK_SCAN(50); CHECK_SCAN_SURROUNDED(50); CHECK_DENSE(50);
        CHECK_COMPARE(51); CHECK_COMPARE_SURROUNDED(51); CHECK_SCAN(51); CHECK_SCAN_SURROUNDED(51); CHECK_DENSE(51);
        CHECK_COMPARE(52); CHECK_COMPARE_SURROUNDED(52); CHECK_SCAN(52); CHECK_SCAN_SURROUNDED(52); CHECK_DENSE(52);
        CHECK_COMPARE(53); CHECK_COMPARE_SURROUNDED(53); CHECK_SCAN(53); CHECK_SCAN_SURROUNDED(53); CHECK_DENSE(53);
        CHECK_COMPARE(54); CHECK_COMPARE_SURROUNDED(54); CHECK_SCAN(54); CHECK_SCAN_SURROUNDED(54); CHECK_DENSE(54);
        CHECK_COMPARE(55); CHECK_COMPARE_SURROUNDED(55); CHECK_SCAN(55); CHECK_SCAN_SURROUNDED(55); CHECK_DENSE(55);
        CHECK_COMPARE(56); CHECK_COMPARE_SURROUNDED(56); CHECK_SCAN(56); CHECK_SCAN_SURROUNDED(56); CHECK_DENSE(56);
        CHECK_COMPARE(57); CHECK_COMPARE_SURROUNDED(57); CHECK_SCAN(57); CHECK_SCAN_SURROUNDED(57); CHECK_DENSE(57);
        CHECK_COMPARE(58); CHECK_COMPARE_SURROUNDED(58); CHECK_SCAN(58); CHECK_SCAN_SURROUNDED(58); CHECK_DENSE(58);
        CHECK_COMPARE(59); CHECK_COMPARE_SURROUNDED(59); CHECK_SCAN(59); CHECK_SCAN_SURROUNDED(59); CHECK_DENSE(59);
}

static void sweep_60_79(void)
{
        CHECK_COMPARE(60); CHECK_COMPARE_SURROUNDED(60); CHECK_SCAN(60); CHECK_SCAN_SURROUNDED(60); CHECK_DENSE(60);
        CHECK_COMPARE(61); CHECK_COMPARE_SURROUNDED(61); CHECK_SCAN(61); CHECK_SCAN_SURROUNDED(61); CHECK_DENSE(61);
        CHECK_COMPARE(62); CHECK_COMPARE_SURROUNDED(62); CHECK_SCAN(62); CHECK_SCAN_SURROUNDED(62); CHECK_DENSE(62);
        CHECK_COMPARE(63); CHECK_COMPARE_SURROUNDED(63); CHECK_SCAN(63); CHECK_SCAN_SURROUNDED(63); CHECK_DENSE(63);
        CHECK_COMPARE(64); CHECK_COMPARE_SURROUNDED(64); CHECK_SCAN(64); CHECK_SCAN_SURROUNDED(64); CHECK_DENSE(64);
        CHECK_COMPARE(65); CHECK_COMPARE_SURROUNDED(65); CHECK_SCAN(65); CHECK_SCAN_SURROUNDED(65); CHECK_DENSE(65);
        CHECK_COMPARE(66); CHECK_COMPARE_SURROUNDED(66); CHECK_SCAN(66); CHECK_SCAN_SURROUNDED(66); CHECK_DENSE(66);
        CHECK_COMPARE(67); CHECK_COMPARE_SURROUNDED(67); CHECK_SCAN(67); CHECK_SCAN_SURROUNDED(67); CHECK_DENSE(67);
        CHECK_COMPARE(68); CHECK_COMPARE_SURROUNDED(68); CHECK_SCAN(68); CHECK_SCAN_SURROUNDED(68); CHECK_DENSE(68);
        CHECK_COMPARE(69); CHECK_COMPARE_SURROUNDED(69); CHECK_SCAN(69); CHECK_SCAN_SURROUNDED(69); CHECK_DENSE(69);
        CHECK_COMPARE(70); CHECK_COMPARE_SURROUNDED(70); CHECK_SCAN(70); CHECK_SCAN_SURROUNDED(70); CHECK_DENSE(70);
        CHECK_COMPARE(71); CHECK_COMPARE_SURROUNDED(71); CHECK_SCAN(71); CHECK_SCAN_SURROUNDED(71); CHECK_DENSE(71);
        CHECK_COMPARE(72); CHECK_COMPARE_SURROUNDED(72); CHECK_SCAN(72); CHECK_SCAN_SURROUNDED(72); CHECK_DENSE(72);
        CHECK_COMPARE(73); CHECK_COMPARE_SURROUNDED(73); CHECK_SCAN(73); CHECK_SCAN_SURROUNDED(73); CHECK_DENSE(73);
        CHECK_COMPARE(74); CHECK_COMPARE_SURROUNDED(74); CHECK_SCAN(74); CHECK_SCAN_SURROUNDED(74); CHECK_DENSE(74);
        CHECK_COMPARE(75); CHECK_COMPARE_SURROUNDED(75); CHECK_SCAN(75); CHECK_SCAN_SURROUNDED(75); CHECK_DENSE(75);
        CHECK_COMPARE(76); CHECK_COMPARE_SURROUNDED(76); CHECK_SCAN(76); CHECK_SCAN_SURROUNDED(76); CHECK_DENSE(76);
        CHECK_COMPARE(77); CHECK_COMPARE_SURROUNDED(77); CHECK_SCAN(77); CHECK_SCAN_SURROUNDED(77); CHECK_DENSE(77);
        CHECK_COMPARE(78); CHECK_COMPARE_SURROUNDED(78); CHECK_SCAN(78); CHECK_SCAN_SURROUNDED(78); CHECK_DENSE(78);
        CHECK_COMPARE(79); CHECK_COMPARE_SURROUNDED(79); CHECK_SCAN(79); CHECK_SCAN_SURROUNDED(79); CHECK_DENSE(79);
}

static void sweep_80_99(void)
{
        CHECK_COMPARE(80); CHECK_COMPARE_SURROUNDED(80); CHECK_SCAN(80); CHECK_SCAN_SURROUNDED(80); CHECK_DENSE(80);
        CHECK_COMPARE(81); CHECK_COMPARE_SURROUNDED(81); CHECK_SCAN(81); CHECK_SCAN_SURROUNDED(81); CHECK_DENSE(81);
        CHECK_COMPARE(82); CHECK_COMPARE_SURROUNDED(82); CHECK_SCAN(82); CHECK_SCAN_SURROUNDED(82); CHECK_DENSE(82);
        CHECK_COMPARE(83); CHECK_COMPARE_SURROUNDED(83); CHECK_SCAN(83); CHECK_SCAN_SURROUNDED(83); CHECK_DENSE(83);
        CHECK_COMPARE(84); CHECK_COMPARE_SURROUNDED(84); CHECK_SCAN(84); CHECK_SCAN_SURROUNDED(84); CHECK_DENSE(84);
        CHECK_COMPARE(85); CHECK_COMPARE_SURROUNDED(85); CHECK_SCAN(85); CHECK_SCAN_SURROUNDED(85); CHECK_DENSE(85);
        CHECK_COMPARE(86); CHECK_COMPARE_SURROUNDED(86); CHECK_SCAN(86); CHECK_SCAN_SURROUNDED(86); CHECK_DENSE(86);
        CHECK_COMPARE(87); CHECK_COMPARE_SURROUNDED(87); CHECK_SCAN(87); CHECK_SCAN_SURROUNDED(87); CHECK_DENSE(87);
        CHECK_COMPARE(88); CHECK_COMPARE_SURROUNDED(88); CHECK_SCAN(88); CHECK_SCAN_SURROUNDED(88); CHECK_DENSE(88);
        CHECK_COMPARE(89); CHECK_COMPARE_SURROUNDED(89); CHECK_SCAN(89); CHECK_SCAN_SURROUNDED(89); CHECK_DENSE(89);
        CHECK_COMPARE(90); CHECK_COMPARE_SURROUNDED(90); CHECK_SCAN(90); CHECK_SCAN_SURROUNDED(90); CHECK_DENSE(90);
        CHECK_COMPARE(91); CHECK_COMPARE_SURROUNDED(91); CHECK_SCAN(91); CHECK_SCAN_SURROUNDED(91); CHECK_DENSE(91);
        CHECK_COMPARE(92); CHECK_COMPARE_SURROUNDED(92); CHECK_SCAN(92); CHECK_SCAN_SURROUNDED(92); CHECK_DENSE(92);
        CHECK_COMPARE(93); CHECK_COMPARE_SURROUNDED(93); CHECK_SCAN(93); CHECK_SCAN_SURROUNDED(93); CHECK_DENSE(93);
        CHECK_COMPARE(94); CHECK_COMPARE_SURROUNDED(94); CHECK_SCAN(94); CHECK_SCAN_SURROUNDED(94); CHECK_DENSE(94);
        CHECK_COMPARE(95); CHECK_COMPARE_SURROUNDED(95); CHECK_SCAN(95); CHECK_SCAN_SURROUNDED(95); CHECK_DENSE(95);
        CHECK_COMPARE(96); CHECK_COMPARE_SURROUNDED(96); CHECK_SCAN(96); CHECK_SCAN_SURROUNDED(96); CHECK_DENSE(96);
        CHECK_COMPARE(97); CHECK_COMPARE_SURROUNDED(97); CHECK_SCAN(97); CHECK_SCAN_SURROUNDED(97); CHECK_DENSE(97);
        CHECK_COMPARE(98); CHECK_COMPARE_SURROUNDED(98); CHECK_SCAN(98); CHECK_SCAN_SURROUNDED(98); CHECK_DENSE(98);
        CHECK_COMPARE(99); CHECK_COMPARE_SURROUNDED(99); CHECK_SCAN(99); CHECK_SCAN_SURROUNDED(99); CHECK_DENSE(99);
}

static void sweep_100_119(void)
{
        CHECK_COMPARE(100); CHECK_COMPARE_SURROUNDED(100); CHECK_SCAN(100); CHECK_SCAN_SURROUNDED(100); CHECK_DENSE(100);
        CHECK_COMPARE(101); CHECK_COMPARE_SURROUNDED(101); CHECK_SCAN(101); CHECK_SCAN_SURROUNDED(101); CHECK_DENSE(101);
        CHECK_COMPARE(102); CHECK_COMPARE_SURROUNDED(102); CHECK_SCAN(102); CHECK_SCAN_SURROUNDED(102); CHECK_DENSE(102);
        CHECK_COMPARE(103); CHECK_COMPARE_SURROUNDED(103); CHECK_SCAN(103); CHECK_SCAN_SURROUNDED(103); CHECK_DENSE(103);
        CHECK_COMPARE(104); CHECK_COMPARE_SURROUNDED(104); CHECK_SCAN(104); CHECK_SCAN_SURROUNDED(104); CHECK_DENSE(104);
        CHECK_COMPARE(105); CHECK_COMPARE_SURROUNDED(105); CHECK_SCAN(105); CHECK_SCAN_SURROUNDED(105); CHECK_DENSE(105);
        CHECK_COMPARE(106); CHECK_COMPARE_SURROUNDED(106); CHECK_SCAN(106); CHECK_SCAN_SURROUNDED(106); CHECK_DENSE(106);
        CHECK_COMPARE(107); CHECK_COMPARE_SURROUNDED(107); CHECK_SCAN(107); CHECK_SCAN_SURROUNDED(107); CHECK_DENSE(107);
        CHECK_COMPARE(108); CHECK_COMPARE_SURROUNDED(108); CHECK_SCAN(108); CHECK_SCAN_SURROUNDED(108); CHECK_DENSE(108);
        CHECK_COMPARE(109); CHECK_COMPARE_SURROUNDED(109); CHECK_SCAN(109); CHECK_SCAN_SURROUNDED(109); CHECK_DENSE(109);
        CHECK_COMPARE(110); CHECK_COMPARE_SURROUNDED(110); CHECK_SCAN(110); CHECK_SCAN_SURROUNDED(110); CHECK_DENSE(110);
        CHECK_COMPARE(111); CHECK_COMPARE_SURROUNDED(111); CHECK_SCAN(111); CHECK_SCAN_SURROUNDED(111); CHECK_DENSE(111);
        CHECK_COMPARE(112); CHECK_COMPARE_SURROUNDED(112); CHECK_SCAN(112); CHECK_SCAN_SURROUNDED(112); CHECK_DENSE(112);
        CHECK_COMPARE(113); CHECK_COMPARE_SURROUNDED(113); CHECK_SCAN(113); CHECK_SCAN_SURROUNDED(113); CHECK_DENSE(113);
        CHECK_COMPARE(114); CHECK_COMPARE_SURROUNDED(114); CHECK_SCAN(114); CHECK_SCAN_SURROUNDED(114); CHECK_DENSE(114);
        CHECK_COMPARE(115); CHECK_COMPARE_SURROUNDED(115); CHECK_SCAN(115); CHECK_SCAN_SURROUNDED(115); CHECK_DENSE(115);
        CHECK_COMPARE(116); CHECK_COMPARE_SURROUNDED(116); CHECK_SCAN(116); CHECK_SCAN_SURROUNDED(116); CHECK_DENSE(116);
        CHECK_COMPARE(117); CHECK_COMPARE_SURROUNDED(117); CHECK_SCAN(117); CHECK_SCAN_SURROUNDED(117); CHECK_DENSE(117);
        CHECK_COMPARE(118); CHECK_COMPARE_SURROUNDED(118); CHECK_SCAN(118); CHECK_SCAN_SURROUNDED(118); CHECK_DENSE(118);
        CHECK_COMPARE(119); CHECK_COMPARE_SURROUNDED(119); CHECK_SCAN(119); CHECK_SCAN_SURROUNDED(119); CHECK_DENSE(119);
}

static void sweep_120_139(void)
{
        CHECK_COMPARE(120); CHECK_COMPARE_SURROUNDED(120); CHECK_SCAN(120); CHECK_SCAN_SURROUNDED(120); CHECK_DENSE(120);
        CHECK_COMPARE(121); CHECK_COMPARE_SURROUNDED(121); CHECK_SCAN(121); CHECK_SCAN_SURROUNDED(121); CHECK_DENSE(121);
        CHECK_COMPARE(122); CHECK_COMPARE_SURROUNDED(122); CHECK_SCAN(122); CHECK_SCAN_SURROUNDED(122); CHECK_DENSE(122);
        CHECK_COMPARE(123); CHECK_COMPARE_SURROUNDED(123); CHECK_SCAN(123); CHECK_SCAN_SURROUNDED(123); CHECK_DENSE(123);
        CHECK_COMPARE(124); CHECK_COMPARE_SURROUNDED(124); CHECK_SCAN(124); CHECK_SCAN_SURROUNDED(124); CHECK_DENSE(124);
        CHECK_COMPARE(125); CHECK_COMPARE_SURROUNDED(125); CHECK_SCAN(125); CHECK_SCAN_SURROUNDED(125); CHECK_DENSE(125);
        CHECK_COMPARE(126); CHECK_COMPARE_SURROUNDED(126); CHECK_SCAN(126); CHECK_SCAN_SURROUNDED(126); CHECK_DENSE(126);
        CHECK_COMPARE(127); CHECK_COMPARE_SURROUNDED(127); CHECK_SCAN(127); CHECK_SCAN_SURROUNDED(127); CHECK_DENSE(127);
        CHECK_COMPARE(128); CHECK_COMPARE_SURROUNDED(128); CHECK_SCAN(128); CHECK_SCAN_SURROUNDED(128); CHECK_DENSE(128);
        CHECK_COMPARE(129); CHECK_COMPARE_SURROUNDED(129); CHECK_SCAN(129); CHECK_SCAN_SURROUNDED(129); CHECK_DENSE(129);
        CHECK_COMPARE(130); CHECK_COMPARE_SURROUNDED(130); CHECK_SCAN(130); CHECK_SCAN_SURROUNDED(130); CHECK_DENSE(130);
        CHECK_COMPARE(131); CHECK_COMPARE_SURROUNDED(131); CHECK_SCAN(131); CHECK_SCAN_SURROUNDED(131); CHECK_DENSE(131);
        CHECK_COMPARE(132); CHECK_COMPARE_SURROUNDED(132); CHECK_SCAN(132); CHECK_SCAN_SURROUNDED(132); CHECK_DENSE(132);
        CHECK_COMPARE(133); CHECK_COMPARE_SURROUNDED(133); CHECK_SCAN(133); CHECK_SCAN_SURROUNDED(133); CHECK_DENSE(133);
        CHECK_COMPARE(134); CHECK_COMPARE_SURROUNDED(134); CHECK_SCAN(134); CHECK_SCAN_SURROUNDED(134); CHECK_DENSE(134);
        CHECK_COMPARE(135); CHECK_COMPARE_SURROUNDED(135); CHECK_SCAN(135); CHECK_SCAN_SURROUNDED(135); CHECK_DENSE(135);
        CHECK_COMPARE(136); CHECK_COMPARE_SURROUNDED(136); CHECK_SCAN(136); CHECK_SCAN_SURROUNDED(136); CHECK_DENSE(136);
        CHECK_COMPARE(137); CHECK_COMPARE_SURROUNDED(137); CHECK_SCAN(137); CHECK_SCAN_SURROUNDED(137); CHECK_DENSE(137);
        CHECK_COMPARE(138); CHECK_COMPARE_SURROUNDED(138); CHECK_SCAN(138); CHECK_SCAN_SURROUNDED(138); CHECK_DENSE(138);
        CHECK_COMPARE(139); CHECK_COMPARE_SURROUNDED(139); CHECK_SCAN(139); CHECK_SCAN_SURROUNDED(139); CHECK_DENSE(139);
}

static void sweep_140_159(void)
{
        CHECK_COMPARE(140); CHECK_COMPARE_SURROUNDED(140); CHECK_SCAN(140); CHECK_SCAN_SURROUNDED(140); CHECK_DENSE(140);
        CHECK_COMPARE(141); CHECK_COMPARE_SURROUNDED(141); CHECK_SCAN(141); CHECK_SCAN_SURROUNDED(141); CHECK_DENSE(141);
        CHECK_COMPARE(142); CHECK_COMPARE_SURROUNDED(142); CHECK_SCAN(142); CHECK_SCAN_SURROUNDED(142); CHECK_DENSE(142);
        CHECK_COMPARE(143); CHECK_COMPARE_SURROUNDED(143); CHECK_SCAN(143); CHECK_SCAN_SURROUNDED(143); CHECK_DENSE(143);
        CHECK_COMPARE(144); CHECK_COMPARE_SURROUNDED(144); CHECK_SCAN(144); CHECK_SCAN_SURROUNDED(144); CHECK_DENSE(144);
        CHECK_COMPARE(145); CHECK_COMPARE_SURROUNDED(145); CHECK_SCAN(145); CHECK_SCAN_SURROUNDED(145); CHECK_DENSE(145);
        CHECK_COMPARE(146); CHECK_COMPARE_SURROUNDED(146); CHECK_SCAN(146); CHECK_SCAN_SURROUNDED(146); CHECK_DENSE(146);
        CHECK_COMPARE(147); CHECK_COMPARE_SURROUNDED(147); CHECK_SCAN(147); CHECK_SCAN_SURROUNDED(147); CHECK_DENSE(147);
        CHECK_COMPARE(148); CHECK_COMPARE_SURROUNDED(148); CHECK_SCAN(148); CHECK_SCAN_SURROUNDED(148); CHECK_DENSE(148);
        CHECK_COMPARE(149); CHECK_COMPARE_SURROUNDED(149); CHECK_SCAN(149); CHECK_SCAN_SURROUNDED(149); CHECK_DENSE(149);
        CHECK_COMPARE(150); CHECK_COMPARE_SURROUNDED(150); CHECK_SCAN(150); CHECK_SCAN_SURROUNDED(150); CHECK_DENSE(150);
        CHECK_COMPARE(151); CHECK_COMPARE_SURROUNDED(151); CHECK_SCAN(151); CHECK_SCAN_SURROUNDED(151); CHECK_DENSE(151);
        CHECK_COMPARE(152); CHECK_COMPARE_SURROUNDED(152); CHECK_SCAN(152); CHECK_SCAN_SURROUNDED(152); CHECK_DENSE(152);
        CHECK_COMPARE(153); CHECK_COMPARE_SURROUNDED(153); CHECK_SCAN(153); CHECK_SCAN_SURROUNDED(153); CHECK_DENSE(153);
        CHECK_COMPARE(154); CHECK_COMPARE_SURROUNDED(154); CHECK_SCAN(154); CHECK_SCAN_SURROUNDED(154); CHECK_DENSE(154);
        CHECK_COMPARE(155); CHECK_COMPARE_SURROUNDED(155); CHECK_SCAN(155); CHECK_SCAN_SURROUNDED(155); CHECK_DENSE(155);
        CHECK_COMPARE(156); CHECK_COMPARE_SURROUNDED(156); CHECK_SCAN(156); CHECK_SCAN_SURROUNDED(156); CHECK_DENSE(156);
        CHECK_COMPARE(157); CHECK_COMPARE_SURROUNDED(157); CHECK_SCAN(157); CHECK_SCAN_SURROUNDED(157); CHECK_DENSE(157);
        CHECK_COMPARE(158); CHECK_COMPARE_SURROUNDED(158); CHECK_SCAN(158); CHECK_SCAN_SURROUNDED(158); CHECK_DENSE(158);
        CHECK_COMPARE(159); CHECK_COMPARE_SURROUNDED(159); CHECK_SCAN(159); CHECK_SCAN_SURROUNDED(159); CHECK_DENSE(159);
}

static void sweep_160_160(void)
{
        CHECK_COMPARE(160); CHECK_COMPARE_SURROUNDED(160); CHECK_SCAN(160); CHECK_SCAN_SURROUNDED(160); CHECK_DENSE(160);
}

//      Every band, once. Called once per tier below.
static void sweep(void)
{
        sweep_0_19();
        sweep_20_39();
        sweep_40_59();
        sweep_60_79();
        sweep_80_99();
        sweep_100_119();
        sweep_120_139();
        sweep_140_159();
        sweep_160_160();
}

/*
        Once per tier, not once.

        The wide bodies are chosen at run time, by a byte, and a machine that
        has AVX2 takes that branch every time -- so a whole tier ships having
        never run. The expansion has no tier of its own, but the routine it
        is measured and checked against has three, and the model is what both
        are held to. So the flag is walked down and the sweep repeated.
*/
b32 main(void)
{
        moonwater_cpu_detect();

        /*
                Function-like, so taking the address still names the routine
                rather than expanding: if any of the three macros were object
                like these three lines would not compile.
        */
        b32 (address_to compare_itself)(const address_any, const address_any,
                                        positive) = memory_compare;
        address_any (address_to first_itself)(address_any, b8, positive) =
                memory_first_of;
        address_any (address_to last_itself)(address_any, b8, positive) =
                memory_last_of;

        first_room = room();
        second_room = room();

        if (!first_room || !second_room) {
                string_format(log, "no room to work in\n");
                log_flush();
                return 1;
        }

        checks++;
        if (compare_itself((const address_any)"ab", (const address_any)"ab", 2)
            || first_itself((address_any)"ab", (b8)'b', 2) == null
            || last_itself((address_any)"ab", (b8)'a', 2) == null)
                fail((const p8 address_to)"the routine by its address", 0, 0,
                     "wrong answer");

        p8 found_avx2 = cpu_has_avx2;
        p8 found_avx512 = cpu_has_avx512;

        for (b32 tier = 0; tier < 2; tier++) {
                cpu_has_avx2 = tier ? 0 : found_avx2;
                cpu_has_avx512 = tier ? 0 : found_avx512;

                positive before = failures;
                sweep();

                string_format(log, "  %s: %p checks, %p failures\n",
                              tier ? (const p8 address_to)"narrow"
                                   : (const p8 address_to)"as found",
                              checks, failures - before);
        }

        cpu_has_avx2 = found_avx2;
        cpu_has_avx512 = found_avx512;

        string_format(log, "%p checks, %p failures\n", checks, failures);
        log_flush();

        return failures ? 1 : 0;
}
