#!/usr/bin/env python3
#
#       Writes src/test/exact.c.
#
#       The compiler_memory.c layer expands sizes known where the call is
#       written to a straight line of moves instead of a call, and which line
#       depends on the number. A test that gets its size from a loop counter
#       cannot reach any of them: the size has to be a literal, sitting in the
#       source, for the compiler to fold the choice. So the checks are written
#       out, one per size, by this.
#
#       Sizes run past the point where the expansion stops and the routine
#       takes over again, so the seam is covered from both sides.
#
#           python3 kit/exact.py > src/test/exact.c
#
import sys

TOP = 160               # past the cutoff, so the fallthrough is covered too
GUARD = 32              # bytes either side that nothing is allowed to touch
SLIDE = 40              # how far a move is slid in each direction

out = sys.stdout.write

out('''#include "../compiler_memory.c"
/*
        Every size that is known where the call is written.

        Generated by kit/exact.py -- do not edit by hand; edit that and run it
        again.

        memory_copy, memory_copy_apart and memory_fill expand in place when the
        size is a literal, and the line they expand to depends on the number: eight
        bytes is a pair of moves, forty is a vector and a remainder, two
        hundred is still a call. Nothing that takes its size from a loop
        counter can reach any of that, because the choice is made by the
        compiler, from the token. So every size is written out here.

        Each check runs into a buffer with guard bytes either side, and both
        halves are looked at: that the bytes asked for arrived, and that the
        bytes either side did not move. A size class that reaches one byte too
        far writes into a guard, and a size class that stops one byte short
        leaves the pattern showing.

        memory_copy is the name memmove is an alias for, so it is slid through
        every overlap in both directions: an expansion that stores before it
        has finished loading is correct on every test that does not overlap.
        memory_copy_apart promises nothing about overlap and is only checked
        where the two do not touch.
''')
out(f'''
        {TOP + 1} sizes, {GUARD} guard bytes, {SLIDE} of slide each way.
*/

#define TOP {TOP}
#define GUARD {GUARD}
#define SLIDE {SLIDE}
''')

out('''
static p8 model[TOP];
static p8 arena[GUARD + TOP + GUARD];
static p8 field_room[SLIDE + TOP + SLIDE];
static p8 shadow[SLIDE + TOP + SLIDE];
static p8 temp[TOP];

static positive checks;
static positive failures;

#define FIELD (arena + GUARD)

//      The pattern the guards are set to, and the one the model carries. They
//      differ at every index so a copy that lands one byte off is visible.
static p8 guard_byte(positive i) { return (p8)(0x5a ^ (i * 7)); }
static p8 model_byte(positive i) { return (p8)(0xa5 ^ (i * 13)); }

static void fail(const p8 address_to what, positive size, const p8 address_to why)
{
        failures++;
        string_format(log, "FAIL %s at %p: %s\\n", what, size, why);
}

static void prepare(void)
{
        for (positive i = 0; i < sizeof(arena); i++)
                arena[i] = guard_byte(i);
}

//      Guards on both sides, and the body against whatever it should hold.
static void inspect(const p8 address_to what, positive size,
                    const p8 address_to want, b32 want_is_byte)
{
        checks++;

        for (positive i = 0; i < GUARD; i++)
                if (arena[i] != guard_byte(i)) {
                        fail(what, size, "wrote before the front");
                        return;
                }

        for (positive i = GUARD + size; i < sizeof(arena); i++)
                if (arena[i] != guard_byte(i)) {
                        fail(what, size, "wrote past the end");
                        return;
                }

        for (positive i = 0; i < size; i++) {
                p8 got = FIELD[i];
                p8 expect = want_is_byte ? want[0] : want[i];

                if (got != expect) {
                        fail(what, size, "wrong byte");
                        return;
                }
        }
}

//      What a move means, spelled out, for the slid cases to be judged against.
static void reference_move(p8 address_to to, const p8 address_to from, positive size)
{
        for (positive i = 0; i < size; i++) temp[i] = from[i];
        for (positive i = 0; i < size; i++) to[i] = temp[i];
}

#define CHECK_COPY(K)                                                         \\
        do {                                                                  \\
                prepare();                                                    \\
                memory_copy_apart(FIELD, model, K);                            \\
                inspect((const p8 address_to)"memory_copy_apart", K, model, 0);\\
        } while (0)

#define CHECK_FILL(K)                                                         \\
        do {                                                                  \\
                p8 value = (p8)(0x3c ^ (K));                                  \\
                prepare();                                                    \\
                memory_fill(FIELD, value, K);                                 \\
                inspect((const p8 address_to)"memory_fill", K, &value, 1);    \\
        } while (0)

//      Slid through every overlap the size allows, both directions. The shadow
//      carries the same bytes through the reference, and the two are compared
//      across the whole room, so a store that lands outside the size shows up.
#define CHECK_MOVE(K)                                                         \\
        do {                                                                  \\
                for (b32 slide = -SLIDE; slide <= SLIDE; slide++) {           \\
                        p8 address_to from = field_room + SLIDE;              \\
                        p8 address_to to = from + slide;                      \\
                        p8 address_to shade = shadow + SLIDE + slide;         \\
                                                                              \\
                        for (positive i = 0; i < sizeof(field_room); i++)     \\
                                field_room[i] = shadow[i] = model_byte(i);    \\
                                                                              \\
                        memory_copy(to, from, K);                             \\
                        reference_move(shade, shadow + SLIDE, K);             \\
                                                                              \\
                        checks++;                                             \\
                                                                              \\
                        for (positive i = 0; i < sizeof(field_room); i++)     \\
                                if (field_room[i] != shadow[i]) {             \\
                                        fail((const p8 address_to)"memory_copy", K, \\
                                             "differs from a byte at a time");\\
                                        break;                                \\
                                }                                             \\
                }                                                             \\
        } while (0)

//      Every size, once. Called once per tier below.
static void sweep(void)
{
''')

for k in range(TOP + 1):
    out(f'        CHECK_COPY({k}); CHECK_FILL({k}); CHECK_MOVE({k});\n')

out('''}

/*
        Once per tier, not once.

        The wide bodies are chosen at run time, by a byte, and a machine that
        has AVX2 takes that branch every time -- so a whole tier ships having
        never run. That has happened twice in this tree already: a one byte
        sabotage in the AVX2 path of memory_first_of passed the entire suite
        because every case was shorter than a vector.

        So the flag is walked down and the sweep repeated. The narrow tier is
        what a build with no permission to use vectors gets, and what every
        pre-AVX2 machine gets, and it is checked here on a machine that has
        them.
*/
b32 main(void)
{
        moonwater_cpu_detect();

        for (positive i = 0; i < TOP; i++) model[i] = model_byte(i);

        p8 found_avx2 = cpu_has_avx2;
        p8 found_avx512 = cpu_has_avx512;

        for (b32 tier = 0; tier < 2; tier++) {
                cpu_has_avx2 = tier ? 0 : found_avx2;
                cpu_has_avx512 = tier ? 0 : found_avx512;

                positive before = failures;
                sweep();

                string_format(log, "  %s: %p checks, %p failures\\n",
                              tier ? (const p8 address_to)"narrow"
                                   : (const p8 address_to)"as found",
                              checks, failures - before);
        }

        cpu_has_avx2 = found_avx2;
        cpu_has_avx512 = found_avx512;

        string_format(log, "%p checks, %p failures\\n", checks, failures);
        log_flush();

        return failures ? 1 : 0;
}
''')
