#!/usr/bin/env python3
"""
The inventory, read off the file rather than written beside it.

Fifty odd routines, each written out once per architecture, and the three
blocks are far apart. This is the map, and it is generated because a table
kept by hand is wrong the first time somebody adds a routine and does not
think to come back here.

    python3 kit/compact/inventory.py <file.c>

Replaces whatever inventory is already at the top, or inserts one if there
is none. Run it last: it reports what the passes before it produced.
"""
import re, sys

HEAD = 'The assembly inventory.'

PREAMBLE = '''
        Generated by kit/compact/inventory.py -- do not edit by hand; edit
        the file and run it again.

        A routine's reasoning is written once, in the first block that has
        it, and later blocks carry a line pointing back. That keeps a wrong
        explanation to one edit instead of three, and it does mean reading
        arm64 alone will not always tell you why something is the way it is.

        The floor is baseline instruction sets: x86_64 without BMI, so bsf
        and bsr but not tzcnt or lzcnt; armv8.0-a without SVE; RV64I without
        Zbb, which has no count-leading-zeros at all, and is why the riscv
        blocks build one out of a shift pair. No SIMD anywhere -- kernel code
        cannot touch the vector registers without kernel_fpu_begin -- so
        every wide operation here is SWAR, eight bytes in an integer
        register. All three targets are little endian and the byte position
        arithmetic depends on it.

        The libc names -- strlen, memcpy, strchr and the rest -- are aliases
        onto these, added where the file stops being compiled into a kernel.
        A .set is a second label on the same address, so there is no wrapper
        and no jump, and which names get one depends on who is linking.
'''

def main(path):
    text = open(path).read()
    lines = text.split('\n')

    arch, cur = [None]*len(lines), None
    for i, l in enumerate(lines):
        m = re.match(r'^#(el)?if (X64|ARM64|RISCV64)$', l.strip())
        if m: cur = m.group(2)
        arch[i] = cur

    have, order = {}, []
    for i, l in enumerate(lines):
        m = re.match(r'ASM_FUNC\(([A-Za-z0-9_]+)\)', l.strip())
        if m and arch[i]:
            have.setdefault(m.group(1), set()).add(arch[i])
            if m.group(1) not in order: order.append(m.group(1))

    # Anything still implemented in C as well, so the table is the whole
    # story. A definition sitting under #if defined(WINDOWS) is not one of
    # those: Windows has no assembly here and never did.
    in_c = []
    for i, l in enumerate(lines):
        m = re.match(r'^[A-Za-z_][A-Za-z0-9_ *]*?\b([a-z_][a-z0-9_]*)\s*\(', l)
        if not (m and not l.rstrip().endswith(';') and i+1 < len(lines)
                and lines[i+1].strip() == '{' and m.group(1) in have):
            continue
        if i and lines[i-1].strip() in ('#if defined(WINDOWS)', '#ifdef WINDOWS'):
            continue
        in_c.append(m.group(1))

    rows, gaps = [], []
    for n in sorted(order):
        s = have[n]
        mark = lambda a: 'yes' if a in s else '--'
        if len(s) < 3: gaps.append(n)
        rows.append(f'          {n:<30} {mark("X64"):<7} {mark("ARM64"):<7} {mark("RISCV64")}')

    body = ['/*', f'        {HEAD}', PREAMBLE.rstrip(),
            '', f'        {len(order)} routines, {len(order)-len(gaps)} of them on all three.',
            '', f'          {"routine":<30} {"x86_64":<7} {"arm64":<7} riscv64',
            f'          {"-"*30} {"-"*7} {"-"*7} {"-"*7}']
    body += rows
    if gaps:
        body += ['', '        Not yet on every machine:']
        for n in gaps:
            missing = [a for a in ('X64','ARM64','RISCV64') if a not in have[n]]
            names = {'X64':'x86_64','ARM64':'arm64','RISCV64':'riscv64'}
            body.append(f'          {n} -- missing on ' +
                        ', '.join(names[a] for a in missing))
    if in_c:
        body += ['', '        Assembly, and a C implementation as well:']
        for n in sorted(set(in_c)):
            body.append(f'          {n}')
    body += ['*/', '']
    block = '\n'.join(body)

    old = re.search(r'/\*\n        ' + re.escape(HEAD) + r'.*?\*/\n', text, re.S)
    if old:
        text = text[:old.start()] + block + text[old.end():]
    else:
        anchor = '\n#ifndef STANDARD_MODERN_C\n'
        text = text.replace(anchor, '\n' + block + anchor, 1)
    open(path, 'w').write(text)
    sys.stderr.write(f'inventory: {len(order)} routines, {len(gaps)} not at parity\n')

main(sys.argv[1])
