#!/bin/sh
. script/common

kernel_extract_dir="linux/"
download_artifacts_dir="artifacts/"
keys_dir=$download_artifacts_dir"keys/"
trusted_keys="torvalds@kernel.org gregkh@kernel.org"
kernel_version="6.16"
kernel_download="https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.16.tar.xz"
kernel_pgp="
-----BEGIN PGP SIGNATURE-----
Comment: This signature is for the .tar version of the archive
Comment: git archive --format tar --prefix=linux-6.16/ v6.16
Comment: git version 2.50.1

iQIzBAABCgAdFiEEZH8oZUiU471FcZm+ONu9yGCSaT4FAmiG9nUACgkQONu9yGCS
aT7fERAAlnGWUA+ggUuKlmN2LbmndlFCwyR/tSUjKn7KMlfSumBA1q/UTICPZWoZ
RD726j1yXAi2aUdZSem36Ri5IM8/OdqQgL4IQzBiv39yppH0xlkTVqXMQwI8gPpL
MSfvRUno0D3WeHEY5zircsuj4lTRUb56tBqnFiz1hZ91Z6pWVlNuQV8xfA1lBk/9
PzO6ZAZ16z4KIyyJbD3dtbP1D1L7w8CsJfR9WDun20AbUE06ypKIG8euLwWSmz1X
Sg7j9mSORRF8g0U85t8rYv/b1PN0MC1DnFA1+GN0+UMd4rqMLqqqqLx7LscoYPl2
mJx10uZrSXtaNXBXSKi/FQ/FAhxarJnrF5EMeugPN+Tq5+KjBGccK6D+jjll3MQG
AgDrGTkTo/yUxGDJcjuJBVo0MTChNcnVioQLYOtbQk6lMrHpkgZSSUIfdMbOwfsf
/MhMgj4pKbooEvdeI1J2QdqegwuHUer/ZOatEPrQS/T5hGAXHreG2/wMW9LtInAH
qDKfZyUTYqI3EvvFj6QJuVWdtg2BvLx8aQXAaGr1vrSH9cd9a+N5VhsRKXI4XbE+
L9le/9Ikix1xP9Phn5TBA2AI+FPBdDQTlC7BQdbA/jaqAOYmHuklc6HcDvQRteqq
eTn5vbhF4BoVyS/Yr7emxWvMT/n8svMUvOGgQhFgCTVfgBSPIMg=
=urdi
-----END PGP SIGNATURE-----
"

kernel_tarball=$download_artifacts_dir"linux-$kernel_version.tar"
kernel_archive=$kernel_tarball".xz"

if [ -d $kernel_extract_dir ]; then
    echo $BOLD "Kernel already extracted..." $RESET
    exit 0
fi

extract_kernel() {
    echo $BOLD "Checking kernel signature" $RESET
    gpg --locate-keys $trusted_keys

    unxz -k $kernel_archive

    echo "$kernel_pgp" >$kernel_tarball".sign"

    gpg --verify $kernel_tarball".sign" $kernel_tarball

    tar -xf $kernel_tarball --strip-components=1 -C $kernel_extract_dir

    rm $kernel_tarball

    echo $BOLD "Kernel extracted to $kernel_extract_dir" $RESET
}

is_file $kernel_archive ||
    curl -L $kernel_download -o $kernel_archive

mkdir -p $download_artifacts_dir
mkdir -p $kernel_extract_dir

extract_kernel
