#!/bin/sh
. script/common

kernel_extract_dir="linux/"
download_artifacts_dir="artifacts/"
keys_dir=$download_artifacts_dir"keys/"
trusted_keys="torvalds@kernel.org gregkh@kernel.org"
kernel_version="6.15.3"
kernel_download="https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.15.3.tar.xz"
kernel_pgp="
-----BEGIN PGP SIGNATURE-----
Comment: This signature is for the .tar version of the archive
Comment: git archive --format tar --prefix=linux-6.15.3/ v6.15.3
Comment: git version 2.49.0

iQIzBAABCgAdFiEEZH8oZUiU471FcZm+ONu9yGCSaT4FAmhUFBcACgkQONu9yGCS
aT5P3RAAxEFTUVFJTB61sNYK6xXTk2rY6Q+6TcjDnxPBO5fi3GuHw/jS5qFLlWDN
WwAMtXBy+9uZwnrfPxRsMYBKrNwVM0/7VvAclG/PnWuAbgPG3tpTmkKm0SDmPCCO
NocL6tFm9ijLJsBaimbl1Lg4T+Lado1yoIVyVAImmFKO/12q7zFg+tEkGHKt6Wet
1KvLvDGxTTO1rqDvA796s8htlCY0VCshTHxSYqD/gepx8O0LtTo4QUycaEPn2ADs
Mr/QBAH05YmZmKPw7OrjciKlC5/7LCBPrU3t8NTWzNYsDvzpicZb+Wi8qU2Ocas7
/EaYaTL2Didz92zONaPNYZfYG+lPCOZlFZaf4d2I4khxplu48CIx1l2q0aCEul1O
FaF+tlkWvAOzgXKAtcASKN/oNqhNABp4x/xW9ZG+HEX7bWHxVLZDpgWcd6fr76TI
inU092YSGhqWGJ9eB9G/i8Zafbn+H/cTBLCfV+k4/8HiDHJ3Af0xH5G751Ov1My3
/ijJhlG8vTnjfiSC/OuetFbEZDdLT1bPF4WvbIsQgavDaqDpM2Q34X5XHr8HTtZR
Qr9QpBJNc6oNSNijbByG6SBxQieCf5WuV+mx1El4LoVKLGdpi138dxqECMYtnWEW
XB9Wc5v7xNsYbYs27M7DcAki3pOYxv39/VojRHGTeHQ2EjKWH1Q=
=0kxB
-----END PGP SIGNATURE-----
"

kernel_tarball=$download_artifacts_dir"linux-$kernel_version.tar"
kernel_archive=$kernel_tarball".xz"

if [ -d $kernel_extract_dir ]; then
    echo $BOLD "Kernel already extracted..." $RESET
    exit 0
fi

extract_kernel() {
    echo $BOLD "Checking kernel signature" $RESET
    gpg --locate-keys $trusted_keys

    unxz -k $kernel_archive

    echo "$kernel_pgp" >$kernel_tarball".sign"

    gpg --verify $kernel_tarball".sign" $kernel_tarball

    tar -xf $kernel_tarball --strip-components=1 -C $kernel_extract_dir

    rm $kernel_tarball

    echo $BOLD "Kernel extracted to $kernel_extract_dir" $RESET
}

is_file $kernel_archive ||
    curl -L $kernel_download -o $kernel_archive

mkdir -p $download_artifacts_dir
mkdir -p $kernel_extract_dir

extract_kernel
