#!/bin/sh
. script/common

kernel_extract_dir="linux/"
download_artifacts_dir="artifacts/"
keys_dir=$download_artifacts_dir"keys/"
trusted_keys="torvalds@kernel.org gregkh@kernel.org"
kernel_version="6.15.7"
kernel_download="https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.15.7.tar.xz"
kernel_pgp="
-----BEGIN PGP SIGNATURE-----
Comment: This signature is for the .tar version of the archive
Comment: git archive --format tar --prefix=linux-6.15.7/ v6.15.7
Comment: git version 2.50.1

iQIzBAABCgAdFiEEZH8oZUiU471FcZm+ONu9yGCSaT4FAmh5KN4ACgkQONu9yGCS
aT6YvQ//f+5BiCzGMBZpX17HpZnjnxEfb5E6bNKO9+n8FwC30uMg1NAtUDe2h1jK
hzAOke3nh3I813Y81RFKfKx/N/bfgYhwY8PvaYGPiiEBhw0CICPEYO9Unw12kAfw
pWEw4stOD0ip7egcW5ngaaBKpRjFFCXehuu+8glx9Y6IvM7pE5rDsnEUM4vycYva
r62pwnDH6jB5V/FOa8shnTWRTCvAidMoBWGX8drhRV7lvmFD8OzBm6ASQUIu9I/P
d1ubqji8KeamO5AhOGBdxZmN7Vk/J+y+d13j12u1rSJW9l1wORJCtJ1CgTmSM362
FqYHfbQaglFh/uQjvMS08mWcr/jTYkABN1MsxZlCCUTDEG/mVZUPSo7RVELjqXOp
/48YkfTI6fLuquUlzEQtDiFaUACDSLa1Q31GQOUysQtTZnNLiBMzdVQaOng07aoT
wEJ6Yu4LPOpxjXSkaQ9Z6Xvf2pbJd+BCOdg66N5UW1B6URTflpgjiTMJHD6Wt6aL
SUSMt1mUbmoBJsdIW2CZv3JJRgUQM5iDVZJEvRoeEyb2gs+FRbmP2esKpK20fkR0
Cz/igM1FMvGWSjOWUdtb4+LxZdYmdONupJEYz1W/D032swp0QpGjn3Am8UkaAF4k
c84qlZqK9YVZV/pVtbwG7y/g9vI0W9lPp4FpphcFjYyT8VyqQ4E=
=b4hI
-----END PGP SIGNATURE-----
"

kernel_tarball=$download_artifacts_dir"linux-$kernel_version.tar"
kernel_archive=$kernel_tarball".xz"

if [ -d $kernel_extract_dir ]; then
    echo $BOLD "Kernel already extracted..." $RESET
    exit 0
fi

extract_kernel() {
    echo $BOLD "Checking kernel signature" $RESET
    gpg --locate-keys $trusted_keys

    unxz -k $kernel_archive

    echo "$kernel_pgp" >$kernel_tarball".sign"

    gpg --verify $kernel_tarball".sign" $kernel_tarball

    tar -xf $kernel_tarball --strip-components=1 -C $kernel_extract_dir

    rm $kernel_tarball

    echo $BOLD "Kernel extracted to $kernel_extract_dir" $RESET
}

is_file $kernel_archive ||
    curl -L $kernel_download -o $kernel_archive

mkdir -p $download_artifacts_dir
mkdir -p $kernel_extract_dir

extract_kernel
